jupyter_client/multikernelmanager.py

Creating a new dict throws away any kwargs passed into the function.  For example, the working directory for the kernel is passed in, and then is ignored if we create a new kwargs dict.  The end result is that we can't set the current working directory for a kernel.

Modify existing kwargs dict instead of creating a new one

---

jupyter_client/kernelspecapp.py

Without this, we get a syntax error on python2 in the print around line 111.

Make print function python2-compatible by importing from __future__

---

jupyter_client/kernelspec.py

while we haven't implemented migration

find kernel specs in .ipython/kernels

---

jupyter_client/connect.py
jupyter_client/consoleapp.py

since that's where they go
fixes `qtconsole --existing`
cc @rgbkrk

find connection files in runtime_dir

---

jupyter_client/manager.py

This makes it easier to make a portable Jupyter+kernels setup, because you can specify executable paths for kernels relative to the parent process' prefix, e.g. `argv: ['{prefix}/bin/R', ...]`
Closes jupyter/jupyter_notebook#53

Add prefix to names that get formatted into kernel cmd

---

jupyter_client/kernelspecapp.py

The foloowing line for example:
> print("ipython_kernel not available, can't install its spec.", file=sys.stderr)

import sys because it is used.

---

jupyter_client/kernelspec.py

Because I need to debug it as my installation do not find the Python2
kernel.

Add debug statement to show where the kernelspecs are actually installed.

---

jupyter_client/kernelspec.py
jupyter_client/tests/test_kernelspec.py

kernel_dis is a search path, which means that the first items have highest priority. The priority of the kernel loading was backward, prioritizing system kernels over user kernels.

fix inverted kernelspec priority

---

jupyter_client/kernelspecapp.py
jupyter_client/tests/test_adapter.py

Noticed this when running `jupyter kernelspec`.
```
$ jupyter kernelspec
No subcommand specified. Must specify one of: ['install-self', 'install', 'list']
Manage IPython kernel specifications.
Subcommands
-----------
Subcommands are launched as `ipython kernelspec cmd [args]`. For information on
using subcommand 'cmd', do: `ipython kernelspec cmd -h`.
install-self
[DEPRECATED] Install the IPython kernel spec directory for this Python.
install
Install a kernel specification directory.
list
List installed kernel specifications.
```
Now it reads:
```
$ jupyter kernelspec
No subcommand specified. Must specify one of: ['list', 'install', 'install-self']
Manage Jupyter kernel specifications.
Subcommands
-----------
Subcommands are launched as `jupyter kernelspec cmd [args]`. For information on …
```

Clean up some naming left behinds from migration

---

jupyter_client/adapter.py
jupyter_client/tests/test_adapter.py

we were adapting `oname` to `name`, which was wrong for two reasons:
1. it's actually `name` in practice, not `oname`, despite what the spec doc claimed. This caused an error during adaptation.
2. name isn't actually part of inspect_reply.

name isn't part of inspect_reply

---

jupyter_client/localinterfaces.py

- prefer `ip` to `ifconfig`
- use regex to reduce localization sensitivity in ifconfig output

localization fixes for local IP detection

---

jupyter_client/localinterfaces.py

when i turn on debug i found this:
```python
[D 21:40:41.543 NotebookApp] Connecting to: tcp://127.0.0.1:60504
/Users/dongweiming/.virtualenvs/notebook/src/jupyter-client/jupyter_client/localinterfaces.py:242: UserWarning: Unexpected error discovering local network interfaces: [Errno 2] No such file or directory
warn("Unexpected error discovering local network interfaces: %s" % e)
```
```python
Traceback (most recent call last):
File "/Users/dongweiming/notebook/jupyter_notebook/base/handlers.py", line 369, in wrapper
result = yield gen.maybe_future(method(self, *args, **kwargs))
File "/Users/dongweiming/notebook/jupyter_notebook/services/sessions/handlers.py", line 53, in post
model = sm.create_session(path=path, kernel_name=kernel_name)
File …
```

fix warn exception when get local ip

---

jupyter_client/kernelspec.py
jupyter_client/tests/test_kernelspec.py

deprecate replace arg with a DeprecationWarning that nobody will ever see...
Also return the install destination for use by callers.

always replace existing installations with `kernelspec.install`

---

jupyter_client/manager.py

it can break Python.
Server in one conda env with kernel in another illustrates this problem.
Symptomatic kernel output:
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

Don't allow PYTHONEXECUTABLE env to be inherited by kernel process

---

jupyter_client/manager.py

Fixes manager.client() for recent changes in traitlets.
See jupyter/nbconvert#42

Change how client_factory default is generated

---

docs/messaging.rst

From ipython/ipython#8571. Thanks @stevengj.

Fix description of where language name is stored

---

jupyter_client/kernelspec.py

when adding .ipython/kernels to kernel_dirs. Allow IPython 3 and no IPython at all to be present.
We originally planned to remove this location now that migration is available, but the cost to keeping it is so low that I think we probably should, at least for a cycle or two.

Don't assume IPython ≥ 4 is present

---

jupyter_client/kernelspec.py
jupyter_client/kernelspecapp.py
jupyter_client/tests/test_kernelspec.py

Makes it a little easier to put kernelspecs in virtualenvs or conda envs, and build packages for kernels.

allow installing kernelspecs with a prefix

---

docs/api/client.rst
docs/messaging.rst
jupyter_client/_version.py
jupyter_client/client.py

Adding a `comm_list_[request/reply]` shell message.

Add comm_info_[request/reply] messages

---

jupyter_client/connect.py

allows easy creation of blocking sibling, which can be useful when deferring to the eventloop is undesirable (e.g. qtconsole is_complete).
see jupyter/qtconsole#33

add `blocking_client` method to KernelManager/Class

---

jupyter_client/consoleapp.py

caused missing log-level, generate-config in qtconsole (jupyter/qtconsole#52), console.

add missing base_flags/aliases to mixin flags/aliases

---

jupyter_client/launcher.py
jupyter_client/manager.py

When interrupting the kernel, you usually want to interrupt the kernel process and its children also. To implement this, we run the kernel in a new process group.

Interrupt the kernel and its child processes

---

jupyter_client/adapter.py

Running jupyter notebook with ijulia I got a non working system after the last update. 
The incriminating series of errors was of the form:
```
[C 11:24:59.636 NotebookApp] Malformed message: [b'status', b'<IDS|MSG>', b'f3523709959441960f28345269661ef64ae62f171d15b6803a356a88fb460998', b'{"msg_id":"2960fe5c-a66d-4a7a-a6dc-2f812f76ddab","msg_type":"status","username":"jlkernel","version":"5.0","session":"????"}', b'{"msg_id":"4386FCC4226042EBAF16A1D3E3911179","msg_type":"kernel_info_request","username":"username","version":"5.0","session":"85D1DBF1CC844A80888619E04D55EC30"}', b'{}', b'{"execution_state":"idle"}']
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/notebook/base/zmqhandlers.py", line 184, in _on_zmq_reply
msg = self._reserialize_reply(msg_list, …
```

Fix for: malformed message - 'datetime' not defined error

---

jupyter_client/localinterfaces.py

This patch makes sure that processes spawned by the Jupyter-client will have their windows hidden. This solves jupyter/jupyter#57.

Stop flashing console windows on Windows

---

docs/messaging.rst

It's an ipython-parallel-specific extension (like apply), and shouldn't be included in the Jupyter spec.

remove data_pub from spec

---

jupyter_client/kernelspec.py

Added configurable behavior to KernelSpec for subclassing.
This opens the door for other kernel spec managers to add additional
properties (such as remote hosts for remote kernel, docker image names
for a docker based kernel etc)

Make kernel_spec_class configurable

---

jupyter_client/kernelspec.py
jupyter_client/kernelspecapp.py
jupyter_client/tests/test_kernelspec.py

Closes #66.
cc/ @minrk @Carreau

Add KernelSpecManager.get_all_specs

---

docs/messaging.rst

UUID is a convenient way to generate unique strings,
but these are not fundamentally UUID objects.
closes jupyter/notebook#768

clarify that msg_id, session are strings

---

jupyter_client/consoleapp.py

also make sure the connection file is in the same dir as the original file
Fixes #102
I have tested this like this:
```
PYTHONPATH=~/projects/jupyter_client: ipython console --ssh server --existing kernel-9072.json
```
Afterwards another connection can be made with
```
ipython console --existing kernel-9072-ssh.json
```

Write the new connection file after establishing SSH tunnels

---

jupyter_client/connect.py

There is no need to bind to all interfaces if the kernel is only going to use a specific one anyway.

test for random ports on the interface the kernel will bind to

---

jupyter_client/kernelspec.py
jupyter_client/kernelspecapp.py
jupyter_client/tests/test_kernelspec.py

for removing kernelspecs
and `jupyter kernelspec uninstall` alias, for good measure.
In order to avoid removing data from the ipykernel source directory, I also added KernelSpecManager.ensure_native_kernel configurable, so that the native kernel can be excluded. This is generally useful for people who want to simply turn off that behavior (@damianavila).
closes jupyter/jupyter_core#63

add `jupyter kernelspec remove`

---

jupyter_client/kernelspec.py

Before if this error is raied, it just prints `NoSuchKernel`, and you need to use a debugger to see which kernel it's complaining about. Now the error message printed along with the exception will include the name of the kernel:
```
Exception occurred:
raise NoSuchKernel(kernel_name)
NoSuchKernel: No such kernel named python3
```

Making the NoSuchKernel error produce a more useful error message

---

jupyter_client/launcher.py
jupyter_client/tests/signalkernel.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/test_kernelspec.py
jupyter_client/tests/utils.py

setpgrp seems to cause problems with children spawning subprocesses. setsid doesn't cause the same problems, but has its own issues.
This is WIP because I need to at least add some tests to exercise various subprocesses-of-subprocesses cases.
cc @takluyver who knows more about terminals and process groups than I do.

start new session instead of setpgrp for detaching kernel

---

.travis.yml
requirements.txt

We no longer need a development version of IPython to test against.
The check for setuptools 18.5 seems to be breaking more stuff than I had expected.

Ditch requirements.txt, upgrade setuptools on Travis

---

docs/messaging.rst

Clarify the semantics of the `shutdown_request` and `shutdown_reply` messages.

Update shutdown_request docs

---

jupyter_client/kernelspec.py

I just discovered that if you do `jupyter kernelspec install blah/`, with the trailing slash, it replaces your entire .../kernels/ directory rather than creating a subdirectory. This is because when it finds the kernel name, it gets the empty string rather than the directory name.
This fixes that.

Strip trailing path separators off kernelspec source directory

---

jupyter_client/blocking/client.py
jupyter_client/manager.py

Closes jupyter/nbconvert#217
`start_new_kernel()` has a `startup_timeout` parameter, but it wasn't being used anywhere. I pass it through to `KernelClient.wait_for_ready()`, and raise RuntimeError if it times out. (Maybe should raise something else? TimeoutError? But this is for OS level operations with errno ETIMEDOUT - not sure if we should use it for arbitrary timeouts).
It also checks whether the kernel is still alive, so if the kernel has already died, we don't need to wait 60 seconds before giving up. It will still wait one second trying to get the message from the kernel.
Ping @minrk

Timeout in start_new_kernel if kernel fails to respond

---

docs/messaging.rst
docs/wrapperkernels.rst

This PR solves two issues with the docs related to the `language_info` field of `kernel_info_message`:
The messaging docs suggest that `name` should be the language that implements the kernel (e.g. a python kernel written in C should use `'C'`). Is this correct?
Wrapper kernels also need to provide this field, otherwise I see an error message when trying to save files. In principle this could be provided from the `Kernel.language` field but it's not being done currently.

language_info name doc fixes

---

docs/messaging.rst

Closes #122.
It's a simple fix but it alerts folks to the "Heartbeats" header later on in the docs.
cc: @willingc

Added heartbeat socket under socket list

---

jupyter_client/session.py

avoids duplicate signature errors if one bit of code peeks at headers, but another bit actually handles the message later.

don't store signature if just peeking at headers

---

jupyter_client/multikernelmanager.py
jupyter_client/tests/signalkernel.py

Squashes some warnings from recent traitlets changes.
There's still another issue with KernelClient - it's passed parameters from the connection info which it doesn't use (key and signature_scheme), because it's also passed a reference to a Session object which already has those things. I'm not sure of the neatest way to resolve that.

Avoid passing down unexpected kwargs

---

jupyter_client/connect.py
jupyter_client/manager.py

- `session=True`: include session object itself
- `session=False`: include session info only (key, signature scheme)
We were passing ignored arguments to the constructor, revealed by a recent warning added to traitlets.
related to #128

add session flag to KernelManager.get_connection_info

---

jupyter_client/session.py

allows other code to take over fork-safety, as is planned in ipython/ipykernel#85

make fork-safety check optional

---

jupyter_client/manager.py

This adds ability to use different dict other than os.environ
as the environment for launching the kernel
Fixes #117

Add ability to specify the env dict for launching the kernel

---

docs/api/kernelspec.rst
docs/changelog.rst
jupyter_client/kernelspec.py

- changelog highlights
- document get_all_specs
We should be ready to ship 4.2 after this, unless there's something anyone else would like to make sure to get in.

Prepare docs for 4.2

---

jupyter_client/blocking/client.py
jupyter_client/channels.py
jupyter_client/tests/signalkernel.py
jupyter_client/tests/test_kernelmanager.py

- timeout was backwards in Client.wait_for_ready
- don't start heartbeat in paused state, which causes is_beating() to return False

Fixes for starting a new kernel

---

jupyter_client/blocking/client.py
jupyter_client/client.py
jupyter_client/tests/signalkernel.py

KernelClient.is_alive() checks heartbeat responsiveness, so it can be False early on if the kernel process is slow to start. This can cause `wait_for_ready` to falsely claim the Kernel died before it has finished starting.
The fix is two-fold:
1. Use KernelManager.is_alive when Manager is available (most of the time).
This isn't sensitive to slow startup.
2. When Manager isn't available,
wait for `is_alive()` to become True at least once before entering the wait
for the ready-reply.
cc @jhamrick, @willingc

Fix wait_for_ready() dying early for slow-starting kernels

---

docs/wrapperkernels.rst

`language_info` is now used instead of the separate `language` and `language_version` fields.

Update wrapper kernel docs

---

jupyter_client/kernelspecapp.py

It's been deprecated since 4.0, but we haven't been showing a message when people use it.

warn about deprecation of jupyter kernelspec install-self

---

jupyter_client/kernelspec.py

The underlying method gained an argument, but it wasn't exposed by the function.

Expose prefix argument on install_kernel_spec function

---

jupyter_client/tests/signalkernel.py

Recent changes in ipykernel have made the tests fail because the IPKernelApp subclass used in tests was missing a displayhook attribute.

Make displayhook in signal test kernel app

---

docs/messaging.rst

and update the spec to clarify that it should contain ports for all running channels.
closes #179

Deprecate connect_request/reply

---

docs/api/client.rst
docs/changelog.rst

Includes the new .load_connection_info method in docs, as well as a few other missing methods.
can release after this.

Changelog for 4.4

---

docs/messaging.rst
docs/wrapperkernels.rst

Update links that were redirecting or causing errors when running `make linkcheck`

Update doc links

---

jupyter_client/launcher.py

since it could contain sensitive info like API keys.
PATH is included explicitly, but no other env is logged.
This does hide useful info like PYTHONPATH, locale, etc. but there is no way to maintain a safe language-agnostic env whitelist.
cc @jasongrout
closes jupyter/notebook#1714

don't log full env when starting kernels fails

---

docs/environment.yml
readthedocs.yml

avoids building the docs against the latest release on conda
also remove unused dependencies from docs environment.yml
closes #194

install current version on readthedocs

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py

Adds a `shutdown_wait_time` parameter to kernelspecs, which allows setting the timeout to a greater value (the default is one second, after which the kernel is killed).
This is useful for special kernels that do things on exit, such as closing a remote connection, saving history/state to disk, cleaning up files, etc.
Alternatively users might be able to implement this using a custom Manager, though it is more work.

Make kernel shutdown timeout configuration

---

docs/messaging.rst

it's basically `status=error` without info and ~no kernels implement it, so deprecate in favor of `status='error'`.
cf ipython/ipykernel#190

deprecate status='abort'

---

jupyter_client/launcher.py

According to its docstring, `start_kernel` accepts additional arguments for `Popen`:
https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L217
However, that's failing right now because `launch_kernel` is not doing anything with those arguments.
This PR fixes that :-)
----
By the way, I need to pass additional args to `Popen` in Spyder. so that's why I need this :-)

Make launch_kernel accept additional arguments to Popen

---

.travis.yml
jupyter_client/blocking/client.py
jupyter_client/client.py
jupyter_client/tests/test_client.py
setup.py

Redisplays output, returns reply.
Can be used in #184
Closes #176
cc @dsblank

add BlockingKernelClient.execute_interactive

---

jupyter_client/session.py
jupyter_client/tests/test_session.py

avoids call-time imports in stdlib uuid, which can cause threading issues with Python import locks.
We don't ever need actual UUIDs, we just want random strings, so we could skip UUID's `-` formatting.
closes ipython/ipykernel#193
cc @rkern

reimplement uuid4 in session

---

README.md
docs/wrapperkernels.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

docs/messaging.rst

with a non-ascii bytes literal

make the binary buffer example super-extra-clearly-binary

---

jupyter_client/kernelspec.py
jupyter_client/kernelspecapp.py
jupyter_client/restarter.py

Log.warn has been in deprecation since at least 2.7

Update log.warn to log.warning

---

docs/kernels.rst
jupyter_client/kernelspec.py
jupyter_client/tests/test_kernelspec.py

allow only: ascii letters, numbers, period, hyphen, underscore.
cf https://github.com/jupyterlab/jupyterlab/issues/1018

validate kernelspec names

---

docs/messaging.rst

We have no plans to use anything other than JSON at present.

Remove mention of switching the message serialisation format

---

docs/messaging.rst

The protocol updates for #209, updateable displays.

Updatable Displays

---

jupyter_client/_version.py
jupyter_client/adapter.py
jupyter_client/jsonutil.py
jupyter_client/session.py
jupyter_client/tests/test_jsonutil.py
jupyter_client/tests/test_session.py
setup.py

- use UTC timestamps everywhere
- use common Z format instead of +00:00 for UTC
- naïve timestamps are given local timezone on serialize/deserialize
- use python-dateutil for parsing, local timezone
This should trigger a major version bump because it affects the Python API (existing code that compares timestamps with naïve timestamps will break). It does not affect the message _protocol_ version, because the protocol's definition of timestamp behavior is unchanged, other than resolving the ambiguity that timezone-free timestamps are interpreted as local time.

ensure timestamps are timezone-aware

---

jupyter_client/manager.py

`_control_socket` can be None if `shutdown_kernel` is called more than once.
related to https://github.com/jupyter/notebook/issues/1544

ensure control socket is connected before using it

---

docs/wrapperkernels.rst

At @jdemeyer's suggestion, I put together a packaged, pip-installable version of the echo kernel example, to serve as a reference for kernel authors.
I also fixed a couple of mistakes I spotted in the docs.

Link to complete echo_kernel example repo

---

docs/environment.yml

Currently, RTD is not building 3.6 so we must pin to 3.5 until 3.6 is supported.

Pin Python to 3.5 for RTD build

---

jupyter_client/kernelspec.py

Unlike logging methods, `warnings.warn()` does not do string formatting of its arguments.

Fix usage of warnings.warn()

---

jupyter_client/manager.py

allows kernelspecs to use 'python' as the executable to launch to indicate the parent environment, which in turn should enable Python packages providing kernelspecs to include their kernelspec in a wheel.
With activated environments, this makes no difference because `which python` and `sys.executable` are the same.
The only case where behavior should differ is when the Manager is in an env, but has been launched without activating the env, e.g. by absolute path (`/path/to/env/bin/jupyter notebook`). In this case, the new behavior seems preferable to the old.
This should only be used for *portable* kernelspecs (e.g. in wheels). Absolute paths are preferable wherever available (e.g. conda packages, local install from source).
cf https://github.com/ipython/ipykernel/pull/223

kernelspec: interpret 'python' as sys.executable

---

jupyter_client/connect.py

avoids periodic cleanup of runtime directory
closes #199

set sticky bit on connection files

---

docs/messaging.rst

Reverts #83.
This behavior is not used currently by ipywidgets itself, and would force front end clients (e.g. JuptyerLab) to support dynamic loads of individual modules.  
Removing this allows us to only support explicitly registered comm targets.
We do have the problem that this documentation has been available since the 4.2 release of this library.
cc @jasongrout

Remove docs for target_module

---

docs/messaging.rst

There was an extra space before Introduction > Heartbeat that caused the whole line to be highlighted.

Fixed broken highlighting in messaging.rst

---

docs/changelog.rst
docs/messaging.rst
jupyter_client/_version.py

We forgot to update this field in the 5.0 release. Should cut a 5.0.1 with this promptly.

protocol version is 5.1

---

jupyter_client/blocking/client.py

`__doc__` is None when run with `-OO`, so don't bother trying to build the expanded docstrings for wrapped methods.
closes https://github.com/ipython/ipyparallel/issues/261

handle when python -OO removes docstrings

---

.travis.yml
jupyter_client/tests/test_adapter.py
jupyter_client/tests/test_client.py
jupyter_client/tests/test_connect.py
jupyter_client/tests/test_jsonutil.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/test_kernelspec.py
jupyter_client/tests/test_multikernelmanager.py
jupyter_client/tests/test_public_api.py
jupyter_client/tests/test_session.py
jupyter_client/tests/utils.py
setup.py

instead of nose.
This is just the minimum to switch over - converting `nt.assert_` to bare asserts and genutils decorators to `pytest.mark`. I left all of the `self.assertFoo` alone, since there's no reason to change them once they exist, but new tests can use bare asserts from now on.

Test with pytest

---

jupyter_client/connect.py
jupyter_client/session.py
jupyter_client/tests/test_session.py

and use it when instantiating new Clients with Manager.client()
If multiple Clients are instantiated against the same kernel, they mustn’t share a digest_history because they could all be receiving the same iopub messages which would cause hash collisions.
relevant to https://github.com/jupyter/kernel_gateway/pull/230

add Session.clone

---

jupyter_client/channels.py
jupyter_client/threaded.py

`HBChannel` and `IOLoopThread` both classes were registering a
bound method `_notice_exit` via `atexit.register` which meant
they would never be garbage collected until the process exited.
It is now replaced with a function which instead sets the
`_exiting` class variable instead of attribute on the instances.

Allow HBChannel and IOLoopThread to be garbage collected

---

docs/messaging.rst
jupyter_client/_version.py

cursor_pos with characters after 0x10000 is officially ambiguous with respect to surrogate pairs in versions 5.1 and earlier due to a widespread bug in javascript frontends.
Thus bumps the protocol to 5.2 with the sole change that cursor_pos is no longer ambiguous (i.e. clients that correctly implement cursor_pos in 5.1 can bump to 5.2 with no other changes).
cf #259
cross-refs for frontend implementations:
- https://github.com/sagemathinc/cocalc/issues/1994
- https://github.com/jupyterlab/jupyterlab/issues/2255
- https://github.com/nteract/nteract/issues/1706
- https://github.com/jupyter/notebook/issues/2509
cc @stevengj @rgbkrk @Carreau @blink1073 @williamstein

describe cursor_pos ambiguity and bump protocol to 5.2

---

docs/messaging.rst

The text still said "four sockets" to introduce a list of five. I've rephrased without a number, so that this error will not reappear when additional sockets are added in the future :-)

remove incorrect number of sockets in messaging spec

---

.gitignore
README.md
setup.py

* Update the test deps (`mock` is required)
* Update doc deps (`ipykernel` is required)
* Add a few files to `.gitignore`.
* Small `README.md` update for docs-buidling deps.
(These are the salvageable bits from #275, which attempted to add `tox` for
testing.)

Small deps and gitignore cleanups.

---

docs/api/kernelspec.rst
docs/kernels.rst
jupyter_client/kernelspec.py
jupyter_client/tests/test_kernelspec.py

Currently, the only way for a kernel to offer additional information about its
capabilities is to encode information into the kernel name or display name;
this information can be useful to clients, especially for things like
filtering a list of kernels.
This adds support for a new kernelspec dict field, `metadata`. This allows
kernels to add additional information, which clients can then consume as
needed.
Fixes #273. /cc @rgbkrk

Add a `metadata` field to kernelspecs.

---

jupyter_client/session.py
jupyter_client/tests/test_session.py

zmq.send will fail on non-contiguous buffers
ensures errors due to bad arguments are raise in `Session.send` instead of potentially delayed to the async callback, which is not handled well.
cf https://github.com/ipython/ipykernel/issues/245

check that buffers are contiguous

---

setup.py

When running `python* setup.py install`, the `jupyter-run` script doesn’t get installed without this.
E.g. arch linux uses `python3 setup.py install --prefix="$pkgdir/usr"` to create packages, not bdist.

Always use setuptools if availabe

---

scripts/jupyter-run

Can be pulled additionally to #282, since it’ll make jupyter-run installable on systems without setuptools.

Also install jupyter-run without setuptools

---

jupyter_client/connect.py
jupyter_client/manager.py
jupyter_client/restarter.py
jupyter_client/tests/test_connect.py

Port already in use

---

jupyter_client/connect.py

since it is used when passing to write_connection_file
This comes up in tests with DummyConfigurable with traitlets master, which removes the `Constructor(attr=value)` assignment for non-trait attributes.

ensure kernel_name is defined on ConnectionFileMixin

---

jupyter_client/connect.py

- specifically silence EPERM on the containing directory,
which can happen when using tempfiles.
- when warning is triggered, explain that it's not a big deal and what might happen.
and actually set the sticky bit, which I just realized we weren't doing because I used the wrong variable to update the permissions.
cf discussion in #201
cc @takluyver @AlJohri

Soften and suppress warnings about sticky bits

---

scripts/jupyter-kernelspec
scripts/jupyter-run
setup.py

follow pattern of other packages, requiring setuptools and disabling implicit bdist_egg
follow-up to #282 #283, resolving any inconsistencies for installing in different contexts. Prevents rare no-setuptools installs from ever being different from normal installs.

unconditionally use setuptools

---

jupyter_client/manager.py

I'd like to place some static files in the resource directory on installation, however, I currently have no way of accessing them from the kernel.

Allow to use the resource directory in the kernel command-line

---

jupyter_client/ioloop/manager.py

Make the `KernelRestarter` class used by `IOLoopKernelManager` configurable.

ENH: Make KernelRestarter class configurable.

---

docs/index.rst
docs/kernel_providers.rst
jupyter_client/discovery.py
jupyter_client/manager.py
jupyter_client/tests/test_discovery.py
setup.py

Following jupyter/nbformat#81, this PR introduces extensible kernel finder machinery, to pave the way for different kernel pickers.
The kernel finder machinery would work like this:
* A MetaKernelFinder object holds a collection of different kernel finder objects.
* Each kernel finder has a short ID, and two methods:
* `find_kernels()` yields pairs of id (str) and kernel attributes (dict). The attributes contain information about the kernel. At present this has no required fields, but we'll probably want to require things similar to the language info in `kernel_info_reply`.
* `make_manager(kernel_id)` returns an instance of `KernelManager`, or a subclass, ready to start a kernel of the specified kind.
* The implementation here provides two kernel finders: one using kernel specs (the same …

Prototype new kernel discovery machinery

---

docs/kernels.rst

The old URL points to a "This page has moved"-page

Updated URL for Jupyter Kernels in other languages

---

jupyter_client/ioloop/manager.py
jupyter_client/ioloop/restarter.py
jupyter_client/session.py
jupyter_client/tests/test_session.py

- use IOLoop.current over IOLoop.instance
- drop removed `loop` arg from PeriodicCallback
- deprecate now-unused IOLoopKernelRestarter.loop
pyzmq 17 will be needed to be fully compatible with tornado 5, which runs on asyncio on Python 3.

prepare for tornado 5

---

docs/kernels.rst
docs/messaging.rst
jupyter_client/_version.py
jupyter_client/kernelspec.py
jupyter_client/manager.py

In Erlang I have only on POSIX and only in the newest version some control over the normal runtime signals, in particular SIGINT. However, I can easily pick up and process the respective message on the control socket to interrupt execution.
Can this functionality be added? If yes, I'd continue and document the functionality and add tests. Maybe it would also be good to have the option of not sending an actual signal (via `os.kill`) at all.

Additional to the actual signal, send a message on the control port

---

jupyter_client/kernelapp.py
jupyter_client/tests/test_kernelapp.py
scripts/jupyter-kernel
setup.py

A simple lead in to the 'kernel nanny' work, this adds a command so you can do:
```
jupyter kernel --kernel python
```
I intend this for post-5.0.

Add 'jupyter kernel' command

---

jupyter_client/manager.py

this should allow ipykernel's wheel-installed specs to specify `python3` or `python2` and prevent python2 kernels from launching with sys.executable if the Python version is 3.
The new KernelFinder machinery may make this obsolete, but I think we still need this for ipykernel's wheels to avoid launching with sys.executable.

extend special handling of sys.executable to pythonX[.Y]

---

jupyter_client/manager.py

if killpg is available. Keeps kill_kernel consistent with other signals.
This should cleanup process groups (e.g. multiprocessing subprocesses) and make EADDRINUSE less likely during restart (ipython/ipykernel#274)
when kernels don't cleanup after themselves (ipykernel#290).

kill process group when killing kernel

---

jupyter_client/kernelspec.py

This avoids doing a full scan of kernel specs each time `get_kernel_spec()` is called. It only looks for the resource directory it needs, saving some unnecessary stat calls.
A caching solution could improve performance even more, but would be much more complex - this collects the low-hanging fruit.

Improve performance of get_kernel_spec

---

jupyter_client/kernelspec.py

Catch errors loading kernelspecs and warn, but return info on all *valid* kernels.
See https://github.com/jupyter/notebook/pull/3136

Tolerate invalid kernel specs in get_all_specs()

---

docs/changelog.rst
docs/conf.py
docs/environment.yml

This isn't final - there are a few PRs waiting to land - but I thought I'd make a start on this.

Start writing release notes for 5.2

---

setup.py

we use zmq.eventloop, which generally requires tornado. The polyfill allowing this to be importable without tornado present is going away in a future release of pyzmq.
closes #321

require tornado

---

docs/changelog.rst
setup.py

Du to a likely bug in wheel, the conditional dependency on pytest ends
up being unconditional. Seem like adding parenthesis fix that (as a work
around).
See https://github.com/pypa/setuptools/issues/1242
Closes #324

Parenthesize conditional requirement in setup.py

---

MANIFEST.in

This shrinks the sdist from 2MB to ~250KB... just realized that after
uploading 5.2.1 took way too long. Apparently 5.2.0 alsho shipped built
docs.

Exclude build docs from sdist.

---

.travis.yml

Use the ability to exclude branches as describe there:
- https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
Relatively easy as MrMeeseeks push a known branch format.
This of course cannot be tested until merged and backported, and another
backport triggered.

Tell Travis not to test the push from MrMeeseeks

---

jupyter_client/channels.py
jupyter_client/threaded.py

we could probably avoid this if we registered/unregistered atexit callbacks for instances instead of registering it once for classes at import time
closes #323
Perhaps more hygenic, if more complex alternative that would use instances:
- register atexit callback in `__init__`
- use a weakref to avoid keeping a reference forever
- unregister callback in `__del__`
Attaching it to an instance should prevent any process-teardown issues, since classes don't get deleted while they still have running instances (I'm pretty sure).

handle classes having been torn down in atexit

---

jupyter_client/kernelspec.py
jupyter_client/tests/test_kernelspec.py

on the result of a public overrideable method, which breaks subclasses that don't override get_all_specs
rather than falling back on the public method, which is slower because it looks up the location of a directory we have already found, reserve this optimization for the base class itself, which is the only place this is a safe method to call.
closes #338
I think we should ship a 5.2.2 bugfix upon merging this one and confirming it fixes nb_conda_kernels

avoid calling private method in subclasses of KernelSpecManager

---

docs/changelog.rst

will release 5.2.2 from 5.x after this. I've merged 5.2.x into 5.x, since it only contained the one 5.2.1 change, and 5.x only has changes for 5.2.2.

changelog for 5.2.2

---

jupyter_client/manager.py

This might need to be targeted on 5.x. We were running into an issue where a warning was being issued without `import warnings` being done at the top.

import warnings for 5.2.x

---

jupyter_client/tests/test_session.py

zmq.COPY_THRESHOLD is undefined prior to pyzmq 17, so we need `create=True` to define it in that case.

fix testing patch for pyzmq < 17

---

jupyter_client/manager.py

This restores the ability of using the deprecated `kernel_cmd`, which previously allowed you to run an arbitrary kernel without having to write a kernelspec. Without this, when using `kernel_cmd`, a lookup on an empty `kernel_name` (with `""` as value) was being performed.

return None kernel_spec if kernel_name not set

---

jupyter_client/connect.py
jupyter_client/ssh/__init__.py
jupyter_client/ssh/forward.py
jupyter_client/ssh/tunnel.py
jupyter_client/tests/test_ssh.py

As discussed in https://github.com/ipython/ipython/issues/10934
As this part of code is mainly used in IPython we
agreed to move it from pyzmq. It will be easier to
maintain here and some planned changes in this code
will be easier to apply and release.
Also some code reformatting was applied in `connect.py` file.

Migrate SSH tunneling from pyzmq

---

jupyter_client/threaded.py

The main issue was failing to schedule `ioloop.stop` in the ioloop thread, which is required when tornado is running on asyncio in order to wake the thread. The result of not doing this is hanging forever when trying to exit, e.g. in QtConsole.
There is further cleanup of threadsafety issues with respect to asyncio and tornado objects.
closes https://github.com/jupyter/qtconsole/issues/275
cc @ccordoba12

tornado 5 fixes in ThreadedClient

---

docs/changelog.rst

Will release 5.2.3 from 5.x when this is merged, which has the last known fix for tornado 5 compatibility.

Changelog for 5.2.3

---

jupyter_client/ioloop/manager.py
jupyter_client/manager.py

After analyzing various leaked items when running either Notebook or
Jupyter Kernel Gateway, one item that recurred across each kernel
startup and shutdown sequence was an instance of IOLoopKernelManager.
(Of course, when using JKG, this instance was KernelGatewayIOLoopKernelManager
since it derives from the former.)
The leak is caused by the circular references established in the `self._restarter`
and `self.session.parent` members. This change breaks the circular reference when
the restarter is stopped and during `cleanup()` of the kernel manager.  Once the
references are broken, the kernel manager instance can be garbage collected.

Fix leak of IOLoopKernelManager object

---

jupyter_client/manager.py

After analyzing various leaked items when running either Notebook or
Jupyter Kernel Gateway, one item that recurred across each kernel
startup and shutdown sequence was the Popen object stored in the kernel
manager in `self.kernel`.
The issue is that in normal circumstances, when a kernel's termination
is successful via the ZMQ messaging, the process is never waited for
(which, in this case, is probably unnecessary but advised) nor is the
member variable set to None.  In the failing case, where the message-based
shutdown does not terminate the kernel process, the `_kill_kernel()`
method is used, which performs the `wait()` and _nullifies_ the kernel
member.  This change ensures that sequence occurs in normal situations
as well.

Fix memory leak of kernel Popen object

---

jupyter_client/_version.py

forgot to update the version in master after a release and we've been doing releases from 5.x since then.

master is 6.0-dev

---

jupyter_client/launcher.py

When running Jupyter via pythonw e.g. pythonw -m qtconsole, jupyter_client launches new kernel via python.exe which is a console application on Windows - a side-effect of that is a new empty console window created and shown as long as kernel is running.
This patch adds CREATE_NO_WINDOW 0x08000000 to Windows specific creationflags. This flag is not exported by subprocess module therefore has to be provides numerically.
Read more, e.g.:
https://stackoverflow.com/questions/2935704/running-shell-commands-without-a-shell-window

Prevent creating new console on Windows

---

.travis.yml
jupyter_client/tests/test_session.py
setup.py

3.3is EOL since last year, and pip print warnings in the test-suite.

update python version testing

---

jupyter_client/session.py

Closes #383 and makes `Session.send_raw` compliant with the protocol wire specification (w.r.t. signing optional binary data buffers at the end of messages).
Not sure if this would warrant test cases on the way signatures are handled in the presence of data buffers.

Don't include extra buffers in message signature

---

jupyter_client/consoleapp.py

This removes special treatment of IPython console so that other kernels can get command-line args. This doesn't allow the passing of flags, but does allow filenames, etc. Once this fix is in place, kernels can get these args via self.parent.extra_args

Allow third-party kernels to get additional args

---

jupyter_client/launcher.py

Python 3.7 sets close_fds=True by default, closing the interrupt/parent handles we are trying to pass to the kernel.
We can be more explicit and use the new [STARTUPINFO.lpAttributeList](https://docs.python.org/3/library/subprocess.html?highlight=close_fds#subprocess.STARTUPINFO.lpAttributeList) (the reason for the change in default behavior) in the future to explicitly inherit only these handles, but this preserves the pre-3.7 behavior on 3.7, getting kernels back to working on py37.
closes https://github.com/ipython/ipykernel/issues/374
cf https://github.com/spyder-ide/spyder/issues/8013

set close_fds=False when starting kernels on Windows

---

.travis.yml

to get requires_python support and avoid getting pip that doesn't support py33

install pip 10 on travis python 3.3

---

docs/messaging.rst

Consider the following sequence of events for a kernel.
* Client A sends execution request (id: R1)
* Client B sends execution request (id: R2)
* R1 raises an exception
* Client A receives `execute_reply` with content `{"status": "error", ...}`
* Client B recieves `execute_reply` with content `{"status": "aborted"}`
The documentation says that B should received `abort` rather than `aborted`, but the IPython kernel returns `aborted` (and is probably what it actually should be).
Additionally, the language around `stop_on_error` is confusing (I think the documentation has it backwards but I'm not sure).

Fix documentation error.

---

.travis.yml

pip has changed its default upgrade strategy, even when `--upgrade` is specified to leave known-incompatible old versions installed. Switch to `--upgrade-strategy=eager` to ensure that things are correctly installed.

upgrade pytest

---

jupyter_client/channels.py

When calling `stop` on a `HBChannel`, one has to wait until the sleep command ends. This would allow a much faster shutdown time.

Make closing jupyter client faster

---

docs/kernels.rst

Hi `jupyter-client` team,
During my read through of the docs, I came across a couple of spots that were ambiguous or a bit unclear. This PR aims to clarify a couple of those spots. Thanks for all the hard work on the documentation for jupyter-client. The docs are really amazing!

Docs suggestions

---

docs/environment.yml

This might fix some failures to build on RTD, where Sphinx is failing to import something from the typing module.
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-client/conda/latest/bin/sphinx-build", line 6, in <module>
from sphinx.cmd.build import main
File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-client/conda/latest/lib/python3.5/site-packages/sphinx/cmd/build.py", line 22, in <module>
from sphinx.application import Sphinx
File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-client/conda/latest/lib/python3.5/site-packages/sphinx/application.py", line 34, in <module>
from sphinx.project import Project
File "/home/docs/checkouts/readthedocs.org/user_builds/jupyter-client/conda/latest/lib/python3.5/site-packag …
```

Build docs with Python 3.7 on conda

---

jupyter_client/kernelapp.py

Set the default connection_file such that it preserves an existing configuration. This fixes #381. 
This leaves the behavior the same if nothing is passed in for `--KernelManager.connection_file` and instead uses the `config` as the configuration mechanism for setting the default.

Configure the connection_file if not already done

---

.travis.yml
jupyter_client/client.py
jupyter_client/tests/test_kernelmanager.py
setup.py

This PR adds several new tests which ensure that kernels can be used when started and operated in a multiprocessing context.
Before this change, if the global ZMQ context was initialized before the processed forked, then the child processes _might_ fail. This is easy to do accidentally – run some kernel first in the current process, to check if it works, then farm that same function out to a pool of processes, and things will go poorly. I think this is because ZMQ contexts are not safe after fork. However, switching from using the global ZMQ context to a single ZMQ context per client eliminates the failures.
One could argue that kernels should never be used in multiprocessing contexts, because they are run in a subprocess anyhow, so multiprocessing doesn't provide a better way to escape …

Avoid kernel failures with multiple processes

---

jupyter_client/client.py
jupyter_client/tests/test_kernelmanager.py

**Note**: This might fail, since python versions 3.3 and 3.4 were dropped before this commit – if the tests pass, then backporting might be okay, but if they fail, I'll need some additional advice.

Backport PR #437: Avoid kernel failures with multiple processes

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/tests/test_multikernelmanager.py
jupyter_client/tests/test_session.py

Followup to https://github.com/jupyter/jupyter_client/pull/438 to provide the same thread / process safety as the kernel manager used by nbconvert. This has a small memory overhead to avoid parent processes from deadlocking when operating with concurrency.

Changed zmqContext to not reuse instances

---

.gitignore
jupyter_client/ioloop/manager.py
jupyter_client/multikernelmanager.py

This PR exposes the control channel in the public API, as required in https://github.com/jupyter/jupyter_client/issues/446. The `KernelClient` has not been updated to connect to the Control socket, it might be interesting to do it later.
EDIT: additional changes might be required in `KernelManager`to avoid having another socket trying to connect on the Control channel, but this is not clear to me for now.

Exposes control channel in public API

---

.travis.yml
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/tests/test_multikernelmanager.py
jupyter_client/tests/test_session.py
setup.py

For some reason this backport didn't get auto-generated. #448 Was merged as is to master already.

Backport #488 5.x zmq context isolation

---

docs/messaging.rst

It’s only mentioned at the top that kernel_info_reply (as all replies) has that field.

Harmonize “status” field

---

jupyter_client/manager.py

I had to solve conflicts so the commit is not the same as the one on master. Let me know if this is a problem, and how I can fix it.

[backport #456 to 5.x] call _create_connected_socket to instantiate _control_socket in KernelManager

---

.gitignore
jupyter_client/connect.py
jupyter_client/ioloop/manager.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/tests/test_jsonutil.py
jupyter_client/tests/test_kernelmanager.py

Hello,
Hope you'll find this PR useful.
This PR fixes warnings like these:
- PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
- DeprecationWarning: Session._key_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
- DeprecationWarning: Interpreting naive datetime as local 2013-07-03 16:34:52.249482. Please add timezone info to timestamps.
- DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
Best regards!

Reduce count of warnings

---

.travis.yml
setup.py

Hello,
The main goal of this PR is to clarify for the PyPI users which versions of Python are supported.
These changes also:
- Enable testing for `3.8-dev`
- Replace `3.7-dev` with `3.7` in `.travis.yml`
- Make Travis CI use `xenial`
https://docs.travis-ci.com/user/reference/xenial/
- Remove obsolete `sudo: false`
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Regards!

Declare support for Python 2.7, 3.5, 3.6, and 3.7

---

docs/messaging.rst

This fixes #129 and #443. The resolutions are up for debate, but these are the choices that I believe will require the least code to change - see the issues for details of what I looked at.

Fix ambiguous specification around execution_reply field

---

docs/messaging.rst
jupyter_client/blocking/client.py
jupyter_client/client.py
jupyter_client/clientabc.py
jupyter_client/connect.py
jupyter_client/consoleapp.py
jupyter_client/manager.py
jupyter_client/threaded.py

These came out of conversations with @minrk.
CC also @SylvainCorlay, who I think has been advocating for the deprecation of sending a shutdown message on the shell channel.
Marking as work-in-progress since I plan to work on this more in the near future. But I also think these changes are pretty self-contained, so I wouldn't regret us merging these now and submitting another PR later either.

Updates to the kernel messaging spec

---

docs/messaging.rst

This is adding documentation for
- `debug_[request/reply]`, which are new messages on the `control` channel,
- `debug_event`, which are sent back debugging kernels to the front-end on `IOPub`.

Document debug_[request|reply] and debug_event

---

docs/kernels.rst
jupyter_client/manager.py
jupyter_client/tests/signalkernel.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/utils.py

I've encountered a number of people (including myself) that would like templated environment variable entries in kernelspecs, so I thought I'd implement it add see if this is something useful to the community.
With this change, kernelspec env entries (or even those clients that set `extra_env` on the `KernelManager` instance (along with `kernel_cmd`)) can reference existing env variables using `${ENV_VAR}` within various `env` entries and expect those substitutions to be performed prior to the kernel's launch.
Here's an example kernelspec env entry:
```json
"env": { 
"PYTHONPATH": "my_special_python_path:${PYTHONPATH}", 
"FOO": "BAR", 
"MY_APP_PATH": "my_bin:${PATH}"
}
```
Following the kernel's invocation, it's environment will include the following variable/values:
``` …
```

Add support for templated env entries

---

docs/changelog.rst
jupyter_client/_version.py
jupyter_client/connect.py
jupyter_client/tests/test_connect.py
setup.py

Includes release information, as we should follow the merge directly with a patch release for 5.3.2.

Secure write for connection file

---

jupyter_client/connect.py

Get administrators SID in correct way

Fix Kernel Startup on WIndows

---

.travis.yml
jupyter_client/connect.py
setup.py

Bug fixes for windows issues are going into jupyter_core for secure_write -- we can move to depending on that location to pick up fixes.
@kevin-bates We can bump the setup requirement to 4.5.1 once https://github.com/jupyter/jupyter_core/pull/166 merges and releases.

Secure core import

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py

cc. @kevin-bates @SylvainCorlay

Only cache ports if the cache_ports flag is set to True

---

setup.py

Its use was removed in #483, so we can drop it now.

Remove pywin32 dependency

---

jupyter_client/session.py

I was benchmarking the ipyparallel code and discovered that the scripts where spending a lot of time acquiring msg_ids. 
The msg_id property of the Session class takes a while to run just to get a unique ID. 
To optimise this I changed the msg_id property function to use a message counter and to just return the session_id + message count. This also return a unique ID and runs much faster. 
Using timeit to compare the existing code with my implementation I got these runtimes for 1000 000 calls to session.msg_id: 
| function             | Runtime in seconds |
|----------------------|--------------------|
| Existing msg_id      | 3.2                |
| Reimplemented msg_id | 0.86               |

Session.msg_id optimization

---

docs/wrapperkernels.rst

My customized kernel does something like the following to handle errors
```python
def _do_execute(self,
code,
silent,
store_history=True,
user_expressions=None,
allow_stdin=True):
try:
except Exception as e:
return {
'status': 'error',
'ename': e.__class__.__name__,
'evalue': str(e),
'traceback': [],
'execution_count': self._execution_count,
}
```
which works fine during interactive data analysis or through `Run all cells`. However, papermill does not recognizes the error and returns `0` when it converts notebooks with my kernel. It turns out that a message of type `error` should be sent through `self.send_response` in addition to returning `execute_reply` with `status` of `error`. Although I believe the caller of this `do_execute` function should automatically do this, this PR documents …

Document the handling of error in do_execute

---

jupyter_client/tests/test_kernelapp.py

In working on https://github.com/conda-forge/jupyter_client-feedstock/pull/38 uncovered a new test dependency on `sphinx` which may be spurious... doesn't appear to be used, but figured PR is better than issue, if straightforward.

remove unused sphinx import in test_kernelapp

---

jupyter_client/manager.py

Currently throws this during [tests against 3.8](
https://travis-ci.org/jupyter/jupyter_client/jobs/654391576?utm_medium=notification&utm_source=github_status):
```
/home/travis/build/jupyter/jupyter_client/jupyter_client/manager.py:82: 
SyntaxWarning: "is not" with a literal. Did you mean "!="?
if self._kernel_spec is None and self.kernel_name is not '':
```
Sure, just a warning, but...
- blocked by #518

Address syntax warning for use of "is" against a string literal

---

docs/requirements.txt
readthedocs.yml

docs haven't been building for a few days because installs from conda-forge regularly fail on rtd with out of memory errors these days.
We've no need for conda-only dependencies on rtd for this repo, so might as well use lighter, simpler pip.

readthedocs: install with pip

---

docs/messaging.rst

that would be the wire protocol
closes #520

clarify that the dict view of a message is not part of the versioned protocol

---

jupyter_client/__init__.py
jupyter_client/asynchronous/client.py
jupyter_client/ioloop/__init__.py
jupyter_client/ioloop/manager.py
jupyter_client/ioloop/restarter.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/test_multikernelmanager.py

After a couple failed attempts due to API breakage and incompleteness as documented in PR #425, this PR takes an [approach using subclassing](https://github.com/jupyter/jupyter_client/pull/425#issuecomment-470033289) that @minrk had proposed.  As a result, I felt it best to start anew with the discussion and I will close #425, which will still be useful for background.  With this approach existing applications can continue using the synchronous classes, while applications that desire async kernel management can do so by setting the `kernel_manager_class` traitlet to the appropriate asynchronous form.  As a result, its a fairly clean separation.
`AsyncKernelManager` derives from `KernelManager` and uses async (gen.coroutine) methods where applicable.  Similarly, `AsyncMultiKernelManger` …

Add support for async kernel management via subclassing

---

jupyter_client/ioloop/manager.py

In reviving the async kernel management work in [Notebook](https://github.com/jupyter/notebook/pull/4479) after #428 was merged, I ran into an issue with the control socket since I hadn't applied the ioloop manager portion of #447 to the AsyncIOLoopKernelManager.  This change adds the appropriate `as_zmqstream` entry to the kernel manager and the Notebook issue is no longer present.

Expose control channel on AsyncKernelManager

---

docs/messaging.rst

makes it a little harder to take the implication that the message dict structure is required
also related to #520

further separate the components of messages when describing the basic message structure

---

jupyter_client/manager.py

The issue was revealed in https://github.com/jupyter/nbclient/pull/37 and https://github.com/jupyter/jupyter_server/pull/191.

Subprocess kill is not async

---

jupyter_client/ioloop/manager.py

Since late February the js/services tests have been producing a single failure in one of its kernel auto-restart tests.  This issue was occurring on all notebook PRs irrespective to change - which implied a changed dependency.  Also in late February, we released jupyter_client 6.0.0.  This release consisted of commits more than two years ago.
In looking through the commit history (and knowing I might be a culprit :blush:) I began going through the commits that seemed possible candidates.  Fortunately, the first I picked was the culprit!
It turns out that commit 7a8394d was resetting the `self._restarter` attribute when stopping the restarter.  Although restarts continued working, _auto_ restarts may not have been getting properly performed.
This change retains the restarter instance …

Retain restarter instance on stop

---

jupyter_client/runapp.py

I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …

Fix exception cause in runapp.py

---

jupyter_client/asynchronous/client.py
jupyter_client/blocking/client.py
jupyter_client/session.py
jupyter_client/ssh/tunnel.py

This is a continuation of #552 .

Fix exception causes all over the codebase

---

jupyter_client/kernelapp.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/tests/test_kernelmanager.py
setup.py

As part of kernel manager instance creation, we create new context of ZMQ.
This kernel manager are responsible for managing lifecycle of kernel process.
At the end of kernel process lifecycle we are just simply killing kernel process and not closing ZMQ context. This leaked ZMQ contexts holds sockets and end up exhausting system resources
This PR fixes this by gracefully shutting down ZMQ context during kernel shutdown process
- Enhanced existing tests to track zmq context checks
1. start jupyter server
2. run kernel_lifecycle.sh script 3 times
3. record socket usage
```
kernel_id=$(curl --silent --show-error  -X POST 'localhost:8888/api/kernels' | jq .id | tr -d '"')
echo $kernel_id
read -n 2 -p 'Stop?'
echo 'stopping '
curl -X DELETE "localhost:8888/api/kernels/$kernel_id"
```
``` …
```

[BugFix] [Resource Leak] Gracefully Close ZMQ Context upon kernel shutdown

---

.gitignore
jupyter_client/multikernelmanager.py

This is a backport of a _portion_ of PR #548.  Specifically, we use a shared ZMQ context (by default) from the _`MultiKernelManager`_ that, when enabled, uses the same context across all `KernelManager` instances.  The portion not backported is the ability to create (and destroy) a ZMQ context per `KernelManager`.

Backport zmq leaks fix for MultiKernelManager

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/tests/test_kernelmanager.py

Rather than use version comparisons to determine if the legacy `cleanup()` method should be used - which unnecessarily takes a deprecated route for applications that don't override `cleanup()` in subclasses or override `KernelManager` at all - this checks if an override of both `cleanup()` and `cleanup_resources()` exist.  If only the former, the deprecated route is taken by calling `cleanup()`, otherwise `cleanup_resources()` is called.
Resolves #558

Detect subclass overrides of cleanup methods

---

jupyter_client/manager.py
jupyter_client/tests/signalkernel.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/utils.py
setup.py

This converts the kernel manager tests to the pytest framework. `TestParallel` was already using pytest, so this converts the other tests.  
The subclasses added in #560 are now used in more tests as general subclasses and a specific subclass test now exists.
Note: There was a bug uncovered in `TestParallel` which was not setting the transport correctly.  As a result, the `tcp` transport was used for tests that were meant to be tested using the `ipc` transport.  Of those, the parallel thread and process tests fail using `ipc` and have been temporarily skipped in this PR.

Refactor kernel manager tests for pytest

---

docs/messaging.rst

Cf JEP on the Jupyter Debugger Protocol. https://github.com/jupyter/enhancement-proposals/pull/47

Document that debug request/reply and events follow the DAP specification and document added messages

---

docs/conf.py
jupyter_client/adapter.py
jupyter_client/blocking/channels.py
jupyter_client/blocking/client.py
jupyter_client/connect.py
jupyter_client/jsonutil.py
jupyter_client/kernelspecapp.py
jupyter_client/session.py
jupyter_client/ssh/tunnel.py
jupyter_client/tests/test_jsonutil.py
jupyter_client/tests/test_kernelspec.py
jupyter_client/tests/test_session.py
jupyter_client/tests/utils.py
setup.py

- remove coding cookies
- remove future import statements
- remove 2/3 conditionals
- remove try/excepts around imports which changed

Remove last bits of Python 2 compat code from package.

---

jupyter_client/connect.py
jupyter_client/jsonutil.py
jupyter_client/launcher.py
jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/tests/test_multikernelmanager.py
jupyter_client/tests/test_session.py

- replace use of compat iteritems(dict) with dict.items()
- remove use of no-op cast_bytes_py2 on python 3
- remove use of unicode_type and string_types
FTR, here's the compat module from `ipython_genutils`

Remove more py2/3 compat code

---

jupyter_client/channelsabc.py
jupyter_client/clientabc.py
jupyter_client/managerabc.py

This PR replaces the use of `with_metaclass` with the `metaclass=` kwarg - which is the standard way to set metaclass when defining classes on Python 3. The `with_metaclass` imports have been removed from the modules.
Note that this PR doesn't fix any specific issue that I am aware of. This is just a drive-by cleanup.

Use py3 metaclass syntax

---

jupyter_client/asynchronous/channels.py
jupyter_client/blocking/channels.py
jupyter_client/channels.py
jupyter_client/consoleapp.py
jupyter_client/kernelapp.py
jupyter_client/kernelspecapp.py
jupyter_client/multikernelmanager.py
jupyter_client/runapp.py
jupyter_client/session.py
jupyter_client/tests/signalkernel.py
jupyter_client/tests/utils.py
jupyter_client/threaded.py

This PR replaces the use of `super(_class_name_, self)` with `super()` - which is the standard way to access the inheritance tree on Python 3.

Use python 3 super syntax

---

jupyter_client/manager.py

During a kernel's shutdown, a race condition can occur between the kernel manager and the kernel restarter such that the restarter sees the kernel process has terminated, yet it's view of the kernel manager still thinks its managing an instance.  In such cases, the restarter initiates its restart sequence and, when attempting to kill the kernel, finds that there's now no kernel process being managed.  In such conditions, the kernel manager was raising an exception indicating there's no process to kill.  Instead, it should perform the same action as when there _is_ a process to kill, only to have the signaling fail because there is no longer any process - [which is to ignore that condition](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L476-L486).  This …

Silence kill_kernel when no process is present

---

jupyter_client/manager.py
jupyter_client/tests/test_kernelmanager.py

As mentioned [here](https://github.com/jupyter/jupyter_client/issues/580#issuecomment-691509741), the use of `extra_env` is essentially _rogue code_ that came into existence as part of future work that later was removed from master (or something like that).  These changes remove its use since its existence interferes with the use of the long-deprecated `kernel_cmd` trait.
Fixes #580

Remove extra_env and corresponding test

---

setup.py

Hello,
I have noticed that documentation dependencies are not listed between extras. I am proposing to add them there.

Add documentation dependencies to setup.py

---

README.md

I noticed the link to the contributor guides for docs wasn't resolving so I updated it to the right URL.

Update link to documentation contribution guide

---

jupyter_client/launcher.py

After this patch you'll be able to do this
in a kernel spec:
{
"argv": ["~/the-project/jupyter/kernel/run", "-f", "{connection_file}"],
"display_name": "The Project (dev)",
"language": "python"
}
This can be useful when you are installing kernel with `--user` option
into `/home/my-name/.local/share/jupyter/kernels/` and having your jupyter
notebooks in different subdirectories of `~/the-project/` folder.
In this case kernel for each notebook is started in the notebook's
subdirectory and without `~/` in the spec Jupyter is unable to find a
file for running a custom kernel.

Allow use ~/ in the kernel's command or it's arguments

---

jupyter_client/manager.py

adapt KernelManager._kernel_spec_manager_changed to observe

---

jupyter_client/asynchronous/client.py
jupyter_client/blocking/client.py
jupyter_client/client.py
jupyter_client/tests/signalkernel.py
jupyter_client/tests/test_kernelmanager.py

This changes the logic of `wait_for_ready` to continue sending info request until there is some IOPub message as a response.

retry kernel_info_requests in wait_for_ready

---

jupyter_client/tests/test_session.py

Replace the encoding parameter with raw=False to fix test_session
with msgpack-1.0.0+.  The encoding parameter was already deprecated
in msgpack-0.6.2, and raw=False is compatible with that version too.

Fix test_session with msgpack-1

---

jupyter_client/manager.py

We started seeing failures with this following the new jupyter-client release.
<details>
<summary>Traceback from failing tests</summary>
```
/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/nbval/kernel.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
startup_timeout = 60, kernel_name = 'python3'
kwargs = {'cwd': '/home/runner/work/EXtra-data/EXtra-data/docs', 'stderr': <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>}
def start_new_kernel(startup_timeout=60, kernel_name='python', **kwargs):
"""Start a new kernel, and return its Manager and Client"""
logger.debug('Starting new kernel: "%s"' % kernel_name)
>       km = KernelManager(kernel_name=kernel_name,
kernel_spec_manager=NbvalKernelspecManager()) …
```

Add change parameter needed for observer method

---

jupyter_client/kernelspec.py

In looking into (and reproducing) the issue described in #591, I noticed that `jupyter kernelspec list` didn't produce any `EACCES` issues despite the fact that its list of kernel directories contained a directory in which access was denied.  I found this was because it uses `os.path.isdir()` to _validate_ the directory.  `isdir()` not only handles `EACCES`, but also `ENOTDIR` and `ENOENT` as well.  Since these latter two exceptions were being ignored in `_find_spec_directory()` and given we needed to better handle `EACCES`, it seemed cleaner to also use `os.path.isdir()` here and forgo the additional exception handling altogether.
Fixes #591

Handle inaccessible kernel directories more gracefully

---

jupyter_client/connect.py
jupyter_client/launcher.py
jupyter_client/localinterfaces.py
jupyter_client/session.py
jupyter_client/tests/test_connect.py
jupyter_client/tests/test_kernelspec.py
jupyter_client/tests/utils.py

There was some request on ipython_genutils to drop nose-1 (for
packaging on openSUSE). In many cases I believe ipython_genutils can be
dropped as it was mostly helping with py2/3 compatibility.
This remove the trivial replacement with their equivalent when possible,
including one case where the assigned variable was unused, and ence was
removed.

Some removal of IPython genutils.

---

.github/workflows/main.yml

While troubleshooting CI issues on #617, I found that the excluded `macos-latest` builds were successful on python 3.8 and 3.9.  This update adds those platform/version combos back into the mix.

Enable the macos tests for py3.8 and 3.9

---

jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/tests/test_multikernelmanager.py

This enables the manager to be reused after shutdown_all by:
- Making sure all the cleanup that happens in shutdown_kernel gets called.
- Making sure to await any starting kernels, and also shut them down
Partially addresses #616.

Clean up AsyncMKM's shutdown_all

---

setup.py

Now that IPython 7.20 is out, the jedi pin should no longer be needed :tada:

Unpin jedi

---

jupyter_client/manager.py
jupyter_client/restarter.py

There is a window in which the auto-restarter logic (that detects unexpectedly terminated kernels) can restart a shutdown kernel - whose termination was intended.
Although rare, this has been seen when a Notebook server is terminated with running kernels, at which time it issues shutdown requests for each kernel - while, at the same time, but after the kernel process has terminated, the restarter detects the kernel process's absence and restarts the kernel.
By indicating that the kernel manager has started a (graceful) shutdown of the kernel, the restarter can better-determine the difference between an intended and unintended shutdown - skipping the kernel restart in case of the former.
Resolves #606

Address race condition between shutdown_kernel and restarter

---

docs/changelog.rst
jupyter_client/manager.py
jupyter_client/tests/signalkernel.py
jupyter_client/tests/test_kernelmanager.py

This implements the discussion in #618, to try to more progressively stop
the kernels.
1) this always sends and interrupt before any shutdown requests;
goal being to stop any processing happening that may block any event
loop.
2) sends the shutdown_requests (no changes here).
3) wait 50% of the wait time, and sends a "terminate" in quote as this
depends on your platform/os, and the type of kernel you have.
- if subprocess.Popen calls `.terminate()` which is SIGTERM on unix; the same as
`.kill()` on windows; if not a Popen instance send SIGTERM.
4) wait the other 50% and kills, (same as before).
This does this both on the sync client and async client.
TBD: write tests and docs; and test more properly;

Interrupt and sigterm before sigkill kernel.

---

jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/utils.py

So that we can better ensure that pending changes don't side-effect `KernelManager` subclass implementations, this change adds tests that assert particular methods are called on subclasses that override those methods.  Failures in these tests will likely indicate a breakage in the API contract.

Add tests to ensure KernelManager subclass methods are called

---

docs/changelog.rst
jupyter_client/connect.py
jupyter_client/consoleapp.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/tests/test_connect.py
jupyter_client/utils.py

IPython Genutils seem to start to be troublesome to package for some Linux
Ditributions because of Python2/3 compat. Get rid of it.
It was not in the dependencies anyway...

Remove dependency on ipython_genutils.

---

jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/test_multikernelmanager.py
jupyter_client/tests/utils.py

This is a follow-on to #626 to check subclass call sequences relative to the MultiKernelManager base classes.
Also found that CI was skipping the async tests of the recently added `TestKernelManagerShutDownGracefully` resulting in these warnings:
```
jupyter_client/tests/test_kernelmanager.py::TestKernelManagerShutDownGracefully::test_async_signal_kernel_subprocesses[signaltest-_install_kernel-_ShutdownStatus.ShutdownRequest]
jupyter_client/tests/test_kernelmanager.py::TestKernelManagerShutDownGracefully::test_async_signal_kernel_subprocesses[signaltest-no-shutdown-install_kernel_dont_shutdown-_ShutdownStatus.SigtermRequest]
jupyter_client/tests/test_kernelmanager.py::TestKernelManagerShutDownGracefully::test_async_signal_kernel_subprocesses[signaltest-no-terminate-install_kernel_dont_term …
```

Add tests to ensure MultiKernelManager subclass methods are called

---

setup.py

Pin python>=3.6.1

---

.github/workflows/main.yml
jupyter_client/asynchronous/client.py
jupyter_client/blocking/client.py
jupyter_client/channels.py
jupyter_client/client.py
jupyter_client/ssh/tunnel.py
jupyter_client/threaded.py
jupyter_client/utils.py

@ccordoba12 this should fix the issues you were having with v6.1.13 in spyder. I checked that qtconsole works fine, but it might be worth trying spyder too. Actually I should open PRs in upstream projects with this jupyter_client.

Fix qtconsole issues

---

jupyter_client/channels.py

See https://github.com/jupyter/jupyter_client/issues/640#issue-856223866

Add block=True back to get_msg()

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/utils.py

This change removes the 7-year deprecation of the `kernel_cmd` trait and last year's deprecation of the `cleanup()` method which was replaced with `cleanup_resources()`. 
This is part of #642.

[Release 7.0] Remove deprecations in kernel manager

---

jupyter_client/tests/signalkernel.py
jupyter_client/tests/test_kernelmanager.py
setup.py

While updating the Kernel Provisioning PR with all of the recent changes, I ran into a couple of general issues that appear related to some recent updates to ipykernel (`6.0a5`).  Since we're using the `--pre` option to install test dependencies, I thought I'd add these changes to the primary branch since, in all likelihood, the next PR will encounter them.
1. This updates the test kernel subclass `SignalTestKernel` to use a native coroutine that is used in `TestKernelManagerShutDownGracefully`.
2. The return of the tuple from the previously required `async_generator`-decorated method has been removed (as has `yield_`) since we no longer support Python 3.5.
3. I had to conditionally skip the `TestKernelManagerShutDownGracefully` tests that use `shutdown_request` on Python 3.6 since the …

Update test kernel with native coroutine, remove async_generator dependency

---

jupyter_client/channels.py

If the code tries to exit while calling `self.poller.poll`, the app will freeze until `until_dead` seconds have elapsed. This avoids that outcome.

PR: Don't block on exit

---

jupyter_client/session.py

Ensures messages are unique after fork.
Closes gh-541

Include process ID in message ID

---

docs/messaging.rst

This PR adds documentation for a new debug requets in the protocol.

Added documentation for richInspectVariables request

---

jupyter_client/jsonutil.py
jupyter_client/session.py
jupyter_client/tests/test_jsonutil.py

This would allow making more general changes here. I am also adding serialization of bytes type into base64. 
For more context, this is going in the direction of https://github.com/ipython/ipykernel/issues/706. This allows getting rid of the `json_clean` function, moving the bytes treatment from ipykernel to jupyter_client when actually doing the serializion of the object.

Use a default serializer that is not only for date types

---

docs/messaging.rst

The documentation states that all replies should have a status field and can pass errors also. The python kernel appears to do this and jupyter_kernel_test includes these in its message schema, although to does not currently require their presence. 
I did not add a status to the debug_reply since it follows the DAP.

Add status field to other replies in documentation

---

docs/messaging.rst

The Qt console and the ipython kernel both use a payload source of "edit_magic", not "edit".

Change to edit_magic payload

---

.github/workflows/downstream.yml

Test downstream projects

---

docs/messaging.rst

This is adding the 'debugger' key toe the `kernel_info_reply`message to signal the frontent if it can start a debugging session.
We may map a more complicated structure to this key, to specify subparts of the Debug Adapter protocol that are supported for instance (or any additional requirement).

Added debugger key in kernel_info_reply

---

jupyter_client/manager.py

In preparation for the 7.0 release, I was perusing the changes to `KernelManager` and noticed some "internal" methods (i.e., methods that won't typically be overridden and are called from within "public" methods) had been changed to `async` but didn't have a backward-compatible "non-async" alias.  As a result, applications that subclass `KernelManager` _**and**_ override any of the following methods will not have their overrides called.  
- `pre_start_kernel()`
- `post_start_kernel()`
- `request_shutdown()`
This pull request addresses this issue by introducing the appropriate aliasing thereby restoring the hierarchical call sequence.
Note that these methods were made `async` for `AsyncKernelManager`, but that will be called out in the 7.0 release notes - along with the other changes.

Fix up some async method aliases in KernelManager

---

jupyter_client/channels.py

See https://github.com/jupyter/jupyter_client/pull/641#issuecomment-891868964

Remove block parameter from get_msg()

---

jupyter_client/kernelspec.py
jupyter_client/tests/test_kernelspec.py

Partially addresses jupyter/jupyter_client#642 by deprecating `KernelSpecManager.whitelist` in favor of the more descriptive and inclusive `KernelSpecManager.allowed_kernelspecs`.

Rename trait to allowed_kernelspecs

---

CHANGELOG.md

Update changelog for 7.0 Release

---

CHANGELOG.md

Automated Changelog Entry for 7.0.0 on master
After merging this PR run the "Draft Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Version Spec | 7.0.0 |
| Since | 26a16c0c91e245f7403aa27a812fee5e905d2964 |

Automated Changelog Entry for 7.0.0 on master

---

jupyter_client/manager.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/utils.py

Fixup a couple more instances where we were calling the internal method name rather than the "aliased" (for lack of a better term) name.  This prevented some lower-level method overrides in subclasses from being called.  The test which was introduced for this purpose has been extended accordingly.
See https://github.com/jupyter/jupyter_client/issues/682#issuecomment-902260179 for more information.
Resolves #682

Use formal method names when called internally

---

CHANGELOG.md

Automated Changelog Entry for 7.0.1 on master
After merging this PR run the "Draft Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Version Spec | 7.0.1 |
| Since | v7.0.0 |

Automated Changelog Entry for 7.0.1 on master

---

jupyter_client/utils.py

Imports shouldn't have side effects like this.
I know it's annoying, but this kind of process initialization needs to be in *application* startup, not library import, otherwise you can end up overriding other code unintentionally.
Plus, with tornado 6.1 and pyzmq 22, the default proactor loop generally works anyway, even if selector is often a better fit for zmq-based applications.
Related to https://github.com/dask/distributed/issues/5272 I believe

Don't set event loop policy on Windows at import time

---

jupyter_client/connect.py

passing connection_info to constructor passes Session args (key, scheme) to the Client, which trigger warnings for unrecognized arguments
We could also add logic in `ConnectionFileMixin.__init__` to explicitly support all the fields of a connection file in the constructor, which might be nice. But we have the load_info method already.

use load_connection_info(info) when constructing a blocking client

---

jupyter_client/provisioning/factory.py
jupyter_client/tests/test_provisioning.py

There have been a few instances of users reporting that they can't run kernels due to the `local-provisioner` not being available.  However, this provisioner is registered in the current jupyter_client package, yet when the package searches for the default provisioner (i.e., `local-provisioner`) it is not found.
- https://discourse.jupyter.org/t/kernel-python-3-is-referencing-a-kernel-provisioner-local-provisioner-that-is-not-available-ensure-the-appropriate-package-has-been-installed-and-retry/10436
- https://github.com/Anaconda-Platform/nb_conda_kernels/issues/209
It turns out that in certain circumstances, which remain a mystery to me, there can be multiple _dist-info_ directories present related to `jupyter_client` - one representing the previous release (6.x - which does not include …

Address missing local-provisioner scenario

---

CHANGELOG.md

Automated Changelog Entry for 7.0.3 on master
| Version Spec | 7.0.3 |
| Since | v7.0.2 |

Automated Changelog Entry for 7.0.3 on master

---

jupyter_client/manager.py

fix kernel can only resstart once  issue
fix issue https://github.com/jupyter/jupyter_client/issues/689

fix kernel can only restart once issue

---

jupyter_client/jsonutil.py
jupyter_client/tests/test_jsonutil.py

ipykernel's `json_clean` used to support generators, iterables, and int/float like types, this adds support for them

Fix json_default so that it's closer to what ipykernel had before

---

jupyter_client/tests/test_utils.py
jupyter_client/utils.py

Clean up the pending task

---

CHANGELOG.md

Automated Changelog Entry for 7.0.4 on master
| Version Spec | 7.0.4 |
| Since | v7.0.3 |

Automated Changelog Entry for 7.0.4 on master

---

jupyter_client/provisioning/factory.py

In my change to address the ["missing" local-provisioner](https://github.com/jupyter/jupyter_client/pull/692), I used a deprecated method (`warn()`) to log the warning message (sigh).  This pull request updates the method to `warning()`.

Use logger.warning instead of deprecated warn method

---

jupyter_client/session.py

it doesn't offer anything useful in 2021, and causes issues with older pyzmq and simplejson.
closes #702

avoid use of deprecated zmq.utils.jsonapi

---

jupyter_client/jsonutil.py
jupyter_client/session.py

As discussed in https://github.com/jupyter/jupyter_client/pull/706#discussion_r719308921
Fix https://github.com/jupyter-widgets/pythreejs/issues/366 and fix https://github.com/jupyter/jupyter_client/issues/701

Fallback to the old ipykernel "json_clean" if we are not able to serialize a JSON message

---

CHANGELOG.md

Automated Changelog Entry for 7.0.6 on master
| Version Spec | 7.0.6 |
| Since | v7.0.5 |

Automated Changelog Entry for 7.0.6 on master

---

jupyter_client/ioloop/restarter.py
jupyter_client/provisioning/provisioner_base.py
jupyter_client/restarter.py
jupyter_client/tests/problemkernel.py
jupyter_client/tests/test_restarter.py

Resolves #715.
There is a small change in the behavior of `KernelRestarter.poll()` and the async variant that should be considered whether it is appropriate (or if a better alternative exists). I.e. https://github.com/jupyter/jupyter_client/commit/2fabf92276dc56823cdf18691556e9a2aea37152 . The other parts should be uncontroversial.

Improve restarter logic

---

.github/workflows/main.yml
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/test_kernelspec.py
jupyter_client/tests/test_multikernelmanager.py
jupyter_client/tests/utils.py

Add `MultiKernelManager.use_pending_kernels` to use a created kernel before the process has started, based on original discussion in [`jupyter_server`](https://github.com/jupyter-server/jupyter_server/issues/592).
Add a `KernelManager.ready` property to that resolves when the process has started for the first time.
Refuse to restart a kernel that has not been fully started - we could also decide to wait if it has been launched but not fully started.
Consumers using `use_pending_kernels` should wait for the `ready` future before attempting to communicate with the kernel.
This change will correspond to a change in [`jupyter_server`](https://github.com/jupyter-server/jupyter_server/pull/593), where the server will use the `ready` future before connecting the websocket.  
Web clients will …

Add support for pending kernels

---

CHANGELOG.md

Automated Changelog Entry for 7.1.0 on master
| Version Spec | 7.1.0 |
| Since | v7.0.6 |

Automated Changelog Entry for 7.1.0 on master

---

docs/provisioning.rst

the RbacProvisioner `pre_launch` function should return a Dict, not a coroutine[Dict]

[DOC] improve kernel provisioner doc

---

docs/messaging.rst

As requested in #520 
Changelog goes back to 5.0 (inclusive), when we started tracking these things well and third-party implementations really got going.
Marked as draft because I'm not sure this is the right way to do it. The changelog info is entirely redundant with the `version changed/added/deprecated` notes (that's where I got the changes), so it means every time we document a change, we must do it twice.
Since Sphinx is fancy about roles, maybe there's a better *automated* way to display this information twice? Or maybe we should *replace* the local-to-the-message change notes with the changelog? I'm not sure. For me, the version changed notes near the messages that have changed seems preferable, but as brought up in #520 it's not efficient for a Kernel author who implements …

add changelog for message spec

---

.github/workflows/check-release.yml
.github/workflows/downstream.yml
.github/workflows/main.yml

- Fixes #728 
- Adds testing against Python 3.10
- Uses `base-setup` from `jupyterlab/maintainer-tools` for cleanup

Test against all kernels in jupyter kernel test and clean up CI

---

.github/workflows/downstream.yml
docs/index.rst
docs/pending-kernels.rst
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/tests/test_multikernelmanager.py

Two changes in this PR, summarized below. This work is a follow-up to #712 
Makes `shutdown_kernel` also show the kernel in a pending state. Since the KernelManager is still managing a process while it's shutting down, which might take a long time, I think this should show as a pending state too.
Also, after working with pending kernels a bit, I believe it makes the most sense to make the `KernelManager` responsible for _reporting_ the kernel's pending state, while the layer that sits above the KernelManager, e.g. `MultiKernelManager`, responsible for _reacting_ to that state.
This essentially means removing *all* `self.ready` checks in the individual KernelManager. For example, 
https://github.com/jupyter/jupyter_client/blob/30823666344c9d03daa7330a81caedd04a6a53a6/jupyter_client/manager. …

Further improvements to pending kernels managment

---

CHANGELOG.md

Automated Changelog Entry for 7.1.1 on main
| Version Spec | 7.1.1 |
| Since | v7.1.0 |

Automated Changelog Entry for 7.1.1 on main

---

jupyter_client/multikernelmanager.py

Attempt at fixing https://github.com/jupyterlab/jupyterlab/issues/11886.
According to the comment above:
https://github.com/jupyter/jupyter_client/blob/263173095ceab87a572937f21f843886ffe356f1/jupyter_client/multikernelmanager.py#L262
This branch of the code should be waiting for the kernel to be ready.
This change seems to be fixing the issue noticed in JupyterLab in https://github.com/jupyterlab/jupyterlab/issues/11886.
Example run: https://github.com/jupyterlab/jupyterlab/runs/4894046802?check_suite_focus=true from https://github.com/jupyterlab/jupyterlab/pull/11887

Await `kernel.ready` in `_async_shutdown_kernel`

---

CHANGELOG.md

Automated Changelog Entry for 7.1.2 on main
| Version Spec | 7.1.2 |
| Since | v7.1.1 |

Automated Changelog Entry for 7.1.2 on main

---

jupyter_client/provisioning/local_provisioner.py

Per [this comment in #104](https://github.com/jupyter/jupyter_client/issues/104#issuecomment-1027506791), we should restore the behavior that signaling the process group is preferred over the Popen `kill()` and `terminate()` methods (which essentially signal the process).  This pull request updates the LocalProvisioner to send `SIGKILL`/`SIGTERM` to the process group, prior to falling back to Popen `kill()`/`terminate()`, respectively.
As also noted in the comment, this functionality is masked by the fact that we still prefer a message-based shutdown unless the message-based shutdown fails or an auto-restart event occurs (when the kernel process can no longer be tracked), in which case the "immediate" form of restart occurs (using the signal-based approach).

Prefer sending signals to kernel process group

---

jupyter_client/session.py

`TypeError` are raised when the dictionaries contain invalid keys, which `json_clean` used to handle so we can fallback to it.
cc. @minrk

Json packer: handle TypeError and fallback to old json_clean

---

.github/workflows/main.yml
CHANGELOG.md
docs/provisioning.rst
docs/wrapperkernels.rst
jupyter_client/tests/test_session.py
pyproject.toml
requirements-doc.txt

- Add pytest options
- Add tests for installing from sdist
- Clean up existing workflows
- Test docs with warnings as errors

Add pytest opts and clean up workflows

---

requirements-test.txt

Since 3f8599f56d1d898e54a8116550b024226c985ac4 we always use unittest.mock

Mock is not needed

---

CHANGELOG.md

Automated Changelog Entry for 7.2.0 on main
| Version Spec | minor |
| Since | v7.1.2 |

Automated Changelog Entry for 7.2.0 on main

---

.github/workflows/downstream.yml
.github/workflows/main.yml
.mailmap
.pre-commit-config.yaml
docs/kernels.rst
docs/messaging.rst
docs/pending-kernels.rst
docs/provisioning.rst
docs/wrapperkernels.rst
jupyter_client/connect.py
jupyter_client/kernelspec.py
jupyter_client/launcher.py
jupyter_client/localinterfaces.py
jupyter_client/manager.py
jupyter_client/provisioning/provisioner_base.py
jupyter_client/session.py
jupyter_client/ssh/tunnel.py
jupyter_client/tests/test_adapter.py
jupyter_client/tests/test_connect.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/test_restarter.py
jupyter_client/threaded.py
pyproject.toml
setup.cfg

- Use new `test-sdist` action from `maintainer-tools`
- Remove warning filters fixed in latest `ipykernel`
- Adopt flake8 rules from `jupyter_server`
- Adopt more pre-commit hooks from `jupyter_server`
- Autoupdate pre-commit hooks

More Cleanup

---

CHANGELOG.md

Automated Changelog Entry for 7.2.2 on main
| Version Spec | next |
| Since | v7.2.1 |

Automated Changelog Entry for 7.2.2 on main

---

.github/workflows/main.yml
.pre-commit-config.yaml
README.md

- Make the non-automatic hooks manual and run on CI
- Add doc8 check
- Update contributing docs

Clean up pre-commit

---

.github/workflows/main.yml
.pre-commit-config.yaml
docs/conf.py
jupyter_client/adapter.py
jupyter_client/asynchronous/client.py
jupyter_client/blocking/client.py
jupyter_client/channels.py
jupyter_client/client.py
jupyter_client/connect.py
jupyter_client/consoleapp.py
jupyter_client/kernelapp.py
jupyter_client/kernelspec.py
jupyter_client/kernelspecapp.py
jupyter_client/launcher.py
jupyter_client/localinterfaces.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/provisioning/factory.py
jupyter_client/provisioning/local_provisioner.py
jupyter_client/provisioning/provisioner_base.py
jupyter_client/restarter.py
jupyter_client/runapp.py
jupyter_client/session.py
jupyter_client/ssh/forward.py
jupyter_client/ssh/tunnel.py
jupyter_client/threaded.py
jupyter_client/win_interrupt.py
pyproject.toml
setup.py

Adopt stricter mypy settings and run in pre-commit as a manual hook

Improve mypy config

---

.github/workflows/main.yml
jupyter_client/channels.py
jupyter_client/client.py
jupyter_client/multikernelmanager.py
jupyter_client/tests/test_kernelmanager.py
jupyter_client/tests/test_multikernelmanager.py
jupyter_client/threaded.py
jupyter_client/utils.py
pyproject.toml

Fixes #771 
```
$ jupyter qtconsole
qt.qpa.drawing: Layer-backing can not be explicitly controlled on 10.14 when built against the 10.14 SDK
$
```
Includes improvements made while working on https://github.com/jupyter-server/jupyter_server/pull/792
Also avoids leaving event loops open at exit in a few more places.

Fix shutdown and cleanup behavior

---

CHANGELOG.md

Automated Changelog Entry for 7.3.0 on main
| Version Spec | minor |
| Since | v7.2.2 |

Automated Changelog Entry for 7.3.0 on main

---

jupyter_client/session.py

Added Unicode error correction using following Error Handler errors="surrogateescape" as discussed here https://github.com/jupyter/jupyter_client/issues/778.
Fixes #778

Unicode error correction using Error Handler

---

jupyter_client/client.py

This extra check fixes issue https://github.com/spyder-ide/spyder/issues/17776 in Spyder, which appeared with Jupyter-client 7.3.0.
It only happens when Spyder is closed, but I don't understand very well why. Since it's a small patch, I hope it'll be accepted so that we don't have to subclass `QtKernelClient` on our side for this.

Check that channels exist before asking if they are alive

---

CHANGELOG.md

Automated Changelog Entry for 7.3.1 on main
| Version Spec | 7.3.1 |
| Since | v7.3.0 |

Automated Changelog Entry for 7.3.1 on main

---

pyproject.toml

Hatch is newly added pypa backend with more flexibility, and helps avoid https://github.com/pypa/pip/issues/11110, which is breaking builds.

Use hatch backend

---

jupyter_client/channels.py
jupyter_client/client.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/threaded.py
pyproject.toml

In some places it appears that `traitlets.Any` is used in place of `typing.Any` for type annotations.
This causes mypy errors in projects which depend on `jupyter_client`, e.g.:
```
euporie/kernel.py: note: In member "start_" of class "NotebookKernel":
euporie/kernel.py:233: error: Argument "stdout" has incompatible type "int"; expected "traitlets.traitlets.Any"  [arg-type]
await self.km.start_kernel(stdout=DEVNULL, stderr=STDOUT)
^
euporie/kernel.py:233: error: Argument "stderr" has incompatible type "int"; expected "traitlets.traitlets.Any"  [arg-type]
await self.km.start_kernel(stdout=DEVNULL, stderr=STDOUT)
^
euporie/kernel.py: note: In member "history_" of class "NotebookKernel":
euporie/kernel.py:670: error: Argument "pattern" to "history" of "KernelClient" has incompatible type …
```

Correct `Any` type annotations.

---

CHANGELOG.md

Automated Changelog Entry for 7.3.3 on main
| Version Spec | next |
| Since | v7.3.2 |

Automated Changelog Entry for 7.3.3 on main

---

.github/workflows/downstream.yml
jupyter_client/threaded.py

- Those changes were done in commit https://github.com/jupyter/jupyter_client/commit/0057186519ed356b822b1b1a0052e4068fccff12, released in version 7.3.2.
- They break Qtconsole and hence Spyder, but I checked locally that a simple revert fixes the problem.
- I added the qtconsole test suite here to avoid future breakages.

Revert latest changes to `ThreadedZMQSocketChannel` because they break Qtconsole

---

CHANGELOG.md

Automated Changelog Entry for 7.3.4 on main
| Version Spec | next |
| Since | v7.3.3 |

Automated Changelog Entry for 7.3.4 on main

---

jupyter_client/client.py

Make _stdin_hook_default async

---

.github/workflows/downstream.yml
jupyter_client/ioloop/restarter.py
pyproject.toml

Since tornado 6.2, the `PeriodicCallback` will now await any callbacks that are awaitable (https://github.com/tornadoweb/tornado/pull/2924). So we no longer need to wrap the async restarter's `poll` method in a `run_sync` call. This allows us to not depend on `nest_asyncio` with the default configuration of jupyter client, so we can avoid some of its pitfalls (e.g. https://github.com/jupyterlab/jupyterlab/issues/11934).

Use tornado 6.2's PeriodicCallback in restarter

---

CHANGELOG.md

Automated Changelog Entry for 7.3.5 on main
| Version Spec | next |
| Since | v7.3.4 |

Automated Changelog Entry for 7.3.5 on main

---

jupyter_client/tests/test_kernelmanager.py

Test `test_start_new_async_kernel` failed in https://github.com/conda-forge/jupyter_client-feedstock/pull/81 because pytest's asyncio mode is `strict`. I don't know why it doesn't fail here.
We can either mark the `start_async_kernel` fixture as a `pytest_asyncio` one, or globally set the mode to `auto`. This PR does the former.

Use pytest_asyncio fixture

---

docs/conf.py
pyproject.toml

The docs build was failing due to a version parsing error in `sphinx_rtd_theme`, so it seemed like a good time to upgrade.

Switch to pydata sphinx theme

---

.github/workflows/downstream.yml
.github/workflows/main.yml
jupyter_client/asynchronous/client.py
jupyter_client/blocking/client.py
jupyter_client/channels.py
jupyter_client/client.py
jupyter_client/ioloop/manager.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/provisioning/local_provisioner.py
jupyter_client/restarter.py
jupyter_client/session.py
jupyter_client/threaded.py
jupyter_client/utils.py
pyproject.toml
tests/conftest.py
tests/test_client.py
tests/test_kernelmanager.py
tests/test_multikernelmanager.py
tests/test_restarter.py
tests/test_session.py
tests/utils.py

- Remove the need for `nest_asyncio` by only calling asynchronous methods on self from within an asynchronous method and using the task runner method described in https://github.com/jupyter/jupyter_client/issues/755
- The blocking channel/client/manager methods call `run_sync` to run ad-hoc and background loop(s) as needed, and use `zmq.Context`.  The async channel/client/manager use `async/await` and `zmq.asyncio.Context`.   
- For session objects, we make all of the methods synchronous and check for futures returned by socket methods, converting them to values as needed.  We had to subclass `ZMQStream` to do the same, but perhaps this logic should go in `pyzmq` itself.
- Add tests for async and threaded clients

Remove nest-asyncio dependency

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py
tests/test_kernelmanager.py
tests/test_multikernelmanager.py

- Make the ready promise less timing-sensitive. 
- Separate out a `shutdown_ready` promise.
- Always return concurrent future in synchronous manager and asyncio future in async manager.

Fix pending kernels again

---

.github/workflows/main.yml
jupyter_client/manager.py
jupyter_client/session.py

- Preserves previous use of `ready` promises, but preserves the promise created in the constructor for initial use.
- Backports a fix from #835 to handle asyncio sockets in `Session.send`

Fix ready promise and session send

---

tests/test_session.py

There was a typo due to which the type of a value was getting compared to itself, so it would always pass.

Fix assertion in `TestSession.test_serialize`

---

jupyter_client/connect.py

cc @kevin-bates 
This prevents a race condition where the kernel launch process is attempting to read the connection file, and we overwrite the file while it is being read.   The symptom is that the kernel fails to start because it cannot decode the JSON in the connection file.
We should backport this fix to 7.x, but I think for 8.x we should change it so that the provisioner is entirely responsible for the handling of the connection file, even if the information lives on the kernel manager.   Nothing would change for the local provisioner.

Workaround for launch bug

---

.github/workflows/main.yml
.pre-commit-config.yaml
.readthedocs.yaml
jupyter_client/adapter.py
jupyter_client/channels.py
jupyter_client/channelsabc.py
jupyter_client/clientabc.py
jupyter_client/connect.py
jupyter_client/consoleapp.py
jupyter_client/kernelspec.py
jupyter_client/kernelspecapp.py
jupyter_client/localinterfaces.py
jupyter_client/managerabc.py
jupyter_client/multikernelmanager.py
jupyter_client/session.py
jupyter_client/ssh/tunnel.py
jupyter_client/threaded.py
jupyter_client/utils.py
pyproject.toml
tests/test_connect.py
tests/test_jsonutil.py
tests/test_kernelapp.py
tests/utils.py

Reduce our maintenance burden and follow the conda-forge policy.
cf [conda-forge.org/docs/user/announcements.html#dropping-python-3-7](https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7)

Support Python 3.8-3.11

---

.pre-commit-config.yaml
jupyter_client/client.py
jupyter_client/connect.py
jupyter_client/consoleapp.py
jupyter_client/ioloop/manager.py
jupyter_client/kernelspec.py
jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/provisioning/factory.py
jupyter_client/provisioning/provisioner_base.py
jupyter_client/runapp.py
pyproject.toml
tests/test_provisioning.py

`entrypoints` has been deprecated in favor of `importlib.metadata`.

Clean up types and remove use of entrypoints

---

jupyter_client/connect.py
jupyter_client/manager.py
tests/test_connect.py

Per the [side discussion between myself and @blink1073](https://github.com/jupyter/jupyter_client/pull/863#issuecomment-1311913872) on PR #863 that was reworking #861, this PR checks that the existing connection file (should one exist) matches the connection information returned from the provisioner and prevents overwriting the connection file in such cases (to avoid the race condition addressed via #861).
These changes also ensure that once the connection file is written (if it didn't already exist) the connection information stored in attributes of `KernelManager` (via the `ConnectionFileMixin`) also matches that returned from the provisioner (which is considered the _truth_).

Reconcile connection information

---

.github/workflows/main.yml
jupyter_client/connect.py
jupyter_client/consoleapp.py
jupyter_client/kernelspecapp.py
jupyter_client/session.py
jupyter_client/ssh/tunnel.py
pyproject.toml
tests/conftest.py
tests/test_client.py
tests/test_consoleapp.py
tests/test_kernelspecapp.py
tests/test_localinterfaces.py
tests/test_restarter.py
tests/test_session.py

- Add coverage for `JupyterConsoleApp`, with attempted ssh tunneling.   Skip checking `ssh/forward.py` since it isn't used and is listed as a demo.
- Add coverage for the kernel spec apps
- Increase `Session` coverage
- Increase `localinterfaces` coverage
- Increase `KernelClient` coverage
- Add Windows coverage

Add more coverage

---

jupyter_client/connect.py
tests/test_connect.py

The changes delivered in #879 did not account for scenarios when ports have changed during restarts - which tends to occur with remote kernels.  As a result, we need to reset the connection file when the connection information returned from the provisioner differs from the file's contents, rather than raise a `ValueError`.  
Although this is probably not an issue in typical situations, it is something that should be fixed.  I apologize to @blink1073 for having not caught this in my initial changes in #879 since two different releases were cut following those changes.

Fix connection reconciliation to handle restarts

---

.github/workflows/main.yml
README.md

Workflow cleanup and add codecov and docs badges.

More CI Cleanup

---

jupyter_client/utils.py
pyproject.toml

Needs https://github.com/jupyter/jupyter_core/pull/315.

Import ensure_async and run_sync from jupyter_core

---

jupyter_client/threaded.py

I know that this is already obsolete with https://github.com/jupyter/jupyter_client/pull/835.  Sometimes, this loop is not marked by nest_asyncio (when calling `run_sync`) so this makes sure that the two eventloops (`asyncio.new_event_loop()` and the other created in `ioloop.IOLoop()`) do not make the system crash. Unfortunately, I can not really give you a reproducible example as I was messing with spyder code when it happened. Feel free to close this PR if you think this is not needed.

Make sure loop is marked with nest_asyncio

---

jupyter_client/consoleapp.py
jupyter_client/kernelspecapp.py
jupyter_client/manager.py
tests/test_multikernelmanager.py

cf https://github.com/jupyter/jupyter_client/issues/833#issuecomment-1333849970

Allow interrupt during restart of pending kernels

---

jupyter_client/multikernelmanager.py
tests/utils.py

The base cases only take **kw, so you can't have subclass also take positional arguments.
It is problematic to allow positional arguments, as is someone code against a subclass it is not swappable for another one.
The latest version of jupyter_server also seem to sometime have subclasses that have the signature with kernel_name first and other with kernel_id first, with is a recipe for disaster if we don't make it kwarg only.
This is I belove not caught by mypy because of multiple reasons:
1) the use of run_sync in a couple of place,
2) method assignement might not be handled by mypy.

MAINT: [_async_]start_kernel should only take kwarg only.

---

jupyter_client/kernelspecapp.py
jupyter_client/manager.py

Cast has minimal if no runtime cost, and is slightly more precise that just ignoring types

MAINT: Proper typing and cast

---

jupyter_client/adapter.py
jupyter_client/asynchronous/client.py
jupyter_client/blocking/client.py
jupyter_client/channels.py
jupyter_client/client.py
jupyter_client/connect.py
jupyter_client/ioloop/manager.py
jupyter_client/ioloop/restarter.py
jupyter_client/kernelspec.py
jupyter_client/manager.py
jupyter_client/session.py
jupyter_client/ssh/__init__.py
jupyter_client/threaded.py
tests/test_client.py

It seem like jupyter_client uses a mix of absolute and relative imports, even in same files, which seem a bit weird.
Normalise everything to relative imports, which should make it a bit easier to detect potential cycles, or higher-level imports.
I've found 6 places that now use `..` to imports somethings, where would potentially want to make some refactor at some point in the future to not import something closer to the root.

MAINT: consistently use relative imports.

---

jupyter_client/threaded.py

- It seems PyZMQ streams return now a list of bytes and not a future, so this was not handled properly.
- This doesn't seem necessary on the `main` branch.

Make Qtconsole work with PyZMQ 25

---

.github/workflows/downstream.yml
jupyter_client/ioloop/restarter.py
jupyter_client/session.py
pyproject.toml
tests/test_session.py

Remove deprecated zmq imports

---

docs/messaging.rst

For consistency with the documentation, since the deprecation of `shutdown_request` on shell was done in 5.4.

Reflect current protocol version in documentation

---

jupyter_client/connect.py
jupyter_client/consoleapp.py
jupyter_client/kernelapp.py
jupyter_client/kernelspec.py
jupyter_client/kernelspecapp.py
jupyter_client/multikernelmanager.py
jupyter_client/runapp.py

In particular f-string:
There are many reason not to use f-string in logs,
- F-strings are eager, so might be slow.
- prevent structured logging or handler to highlight.
- Security (untrusted input can lead to DOS on formatting, https://discuss.python.org/t/safer-logging-methods-for-f-strings-and-new-style-formatting/13802)
- Performance (we can filter before formatting).
But also % formatting in a couple of places.

MAINT: Don't format log in log call.

---

.github/workflows/downstream.yml
jupyter_client/asynchronous/client.py
tests/test_client.py
tests/test_kernelmanager.py
tests/test_multikernelmanager.py

Add papermill downstream check and fix kernel client replies

---

tests/test_jsonutil.py

This PR improves the tests of jsonutil.py. It adds tests to `parse_date` and `extract_dates` by covering some untested cases. Coverage has also slightly increased.
Overall, I created 5 tests to cover some common and boundary cases:
- test_parse_date_invalid
- test_parse_date_valid
- test_parse_date_from_naive
- test_extract_dates_from_str
- test_extract_dates_from_dict
Also, the test `test_extract_dates` was renamed to `test_extract_dates_from_list`.

Improving jsonutil tests

---

jupyter_client/jsonutil.py
tests/test_jsonutil.py

Don't emit a trailng newline in base64-encoded data like 'image/png'

---

jupyter_client/kernelspecapp.py

typo in log -> print migration (#923) resulted in output like:
```
Available kernels:
%s    %s python3                                                           /Users/minrk/conda/share/jupyter/kernels/python3
```
and keep errors written to stderr, not stdout

fix kernelspec print output

---

jupyter_client/threaded.py

not just the underlying socket, because the stream represents event listeners on the socket, and can produce errors or at least warnings if the socket is closed before being unregistered. Or worst case, continue to register the wrong callbacks on a subsequent socket if it uses the freed FD before it's noticed.
related to https://github.com/spyder-ide/spyder/issues/20381

ThreadedZMQStream: close stream before socket

---

jupyter_client/threaded.py

Future allows us to propagate errors across threads, instead of threading.Event, which only waits forever and can result in uninformative hangs if there are errors.
this is related to https://github.com/spyder-ide/spyder/issues/20381 where flush is being called on a closed stream, but the traceback doesn't track to the actual caller of `channel.flush()` because of how it's scheduled.
This shouldn't actually change the behavior, only improve error reporting when e.g. calling flush on a closed channel.
Alternately, we could _choose_ to turn this error into a warning, which would in fact be a change in behavior.

use c.f.Future to wait across threads

---

jupyter_client/connect.py
jupyter_client/provisioning/local_provisioner.py

Allow writing user-relevant information when creating a connection file. As an example, this can fulfill my feature request https://github.com/jupyter/notebook/issues/6936.
Should be work with https://github.com/ipython/ipykernel/pull/1127

Allow kwargs when writting connection_file

---

jupyter_client/manager.py

This addresses issue #878 and #955. Suggested by @kevin-bates.

Make cache_ports configurable with default value of False.

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py
jupyter_client/utils.py

See https://github.com/jupyter-server/jupyter_server/pull/1305.

Support external kernels

---

jupyter_client/session.py
jupyter_client/utils.py

* Do not use datetime.utcnow() that is deprecated in Python 3.12
* Import session.utcnow() into utils instead of reimplementing it

Do not use datetime.utcnow() that is deprecated in Python 3.12

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py

This allow to update the running env of kernels.
This will allow resolves some inconsistencies between kernel restart, and actually stopping and starting a kernel session.
In parsley via a few lines in Jupyter Server in update_session, this will let us update the `__session__` which is supposed to reflect some information about the current session, and help correct ipython/ipykernel#1102 where renaming a notebook is not reflected in the kernel unless you manually stop/start the session, or restart the server.

Allow to update kernels env in between restart.

---

jupyter_client/session.py

See [this error](https://github.com/ipython/ipykernel/actions/runs/6651844622/job/18074668768?pr=1079#step:4:664):
```
Traceback (most recent call last):
File "/Users/runner/work/ipykernel/ipykernel/ipykernel/iostream.py", line 175, in _handle_event
raise e
File "/Users/runner/work/ipykernel/ipykernel/ipykernel/iostream.py", line 171, in _handle_event
event_f()
File "/Users/runner/work/ipykernel/ipykernel/ipykernel/iostream.py", line 638, in _flush
self.session.send(
File "/Users/runner/Library/Application Support/hatch/env/virtual/ipykernel/8WkbHHn4/cov.qt6/lib/python3.11/site-packages/jupyter_client/session.py", line 870, in send
msg["tracker"] = tracker
^^^^^^^
UnboundLocalError: cannot access local variable 'tracker' where it is not associated with a value
```

Fix possibly not defined tracker

---

jupyter_client/manager.py
jupyter_client/multikernelmanager.py
tests/test_manager.py

closes jupyterlab/jupyterlab#15301

BUG: Fix Kwarg only in update_env

---

jupyter_client/manager.py

I think that if it is unused, then it is likely a mistake from the caller that meant to pass a kwarg.
Should it maybe get a deprectation period ?

Unused `*args` in `KernelManager`'s `__init__`

---

docs/kernels.rst
docs/wrapperkernels.rst

Add docs about packaging kernels

---

jupyter_client/asynchronous/client.py
jupyter_client/channels.py
jupyter_client/client.py
pyproject.toml

Use non-blocking zmq Poller

---

jupyter_client/jsonutil.py

...
/usr/lib/python3.13/site-packages/jupyter_client/jsonutil.py:31: in <module>
datetime.strptime("1", "%d")  # noqa
/usr/lib64/python3.13/_strptime.py:573: in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
/usr/lib64/python3.13/_strptime.py:336: in _strptime
format_regex = _TimeRE_cache.compile(format)
/usr/lib64/python3.13/_strptime.py:282: in compile
return re_compile(self.pattern(format), IGNORECASE)
/usr/lib64/python3.13/_strptime.py:270: in pattern
warnings.warn("""\
E   DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
E   and fails to parse leap day. The default behavior will change in Python 3.15
E   to either always raise an exception or to use a different default year (TBD).
E   To avoid …

Avoid a DeprecationWarning on Python 3.13+

---

jupyter_client/jsonutil.py

avoids more complex behavior of general parser, which we don't need since we are already specifying the general format spec as ISO-8601. Also, the general `parse_date` behavior seems to be vulnerable to problems:
- closes https://github.com/ipython/ipykernel/issues/1259
- closes https://github.com/jupyterlab/jupyterlab/issues/16268

use simpler isoparse from dateutil to parse ISO-8601 timestamps

---

jupyter_client/localinterfaces.py

The `netifaces` package has been archived by upstream, and pre-compiled wheels are not available for Python >= 3.10. An alternative is the maintained `psutil` package, and this PR tries to determine network addresses (in `localinterfaces.py`) using this package before falling back to `netifaces` and the other existing methods.

Support psutil for finding network addresses

---

jupyter_client/localinterfaces.py

`public_ips()` is meant to return addresses which might be connectable from other machines, which link-local are not.
closes #1039

don't include link-local addresses (169.254) in public_ips

---

jupyter_client/consoleapp.py
jupyter_client/kernelspec.py
jupyter_client/runapp.py
tests/test_runapp.py

NoSuchKernel used to raise during KernelManager instantiation, but it is now delayed, so our `except NoSuchKernel` isn't catching the error when it's raised anymore.
Access kernel_spec to ensure it's raised where it will be caught.
Also removes a redundant warning log immediately before raising, which prevents complete handling of NoSuchError and produces unavoidable duplicate logs.
Test added for runapp, both regression for #993 and simple exercise for everything working correctly.
closes #993

jupyter-run: avoid traceback for NoSuchKernel

---

docs/messaging.rst

This adds messaging documentation for optional features [JEP92](https://github.com/jupyter/enhancement-proposals/pull/92) and kernel subshells [JEP91](https://github.com/jupyter/enhancement-proposals/pull/91/files).
Summary of changes:
- Optional features [JEP92](https://github.com/jupyter/enhancement-proposals/pull/92):
- Return optional `supported_features` in `kernel_info_reply`.
- Deprecate use of `debugger` in `kernel_info_reply` as this is replaced by `supported_features=['debugger']`. It will have to be a long deprecation period whilst other libraries in the Jupyter ecosystem adopt use of `supported_features`.
- Kernel subshells [JEP91](https://github.com/jupyter/enhancement-proposals/pull/91/files):
- Return `supported_features=['kernel subshells']` in `kernel_info_reply`.
- New …

Add messaging docs for optional features and kernel subshells

---

jupyter_client/localinterfaces.py

Followup to #1033, apparently docstring got copy-pasted from _load_ips_netifaces

Update _load_ips_psutil() docstring

---

jupyter_client/jsonutil.py
tests/test_jsonutil.py

Resolves #1058.
fwiw the (original?) copy of json_clean in https://github.com/ipython/ipykernel/blob/2c212648775646f1c92e8f3e977806dea14186da/ipykernel/jsonutil.py#L160 has date support.

Support date serialization in messages
