jupyter/jupyter_client

- jupyter_client/jsonutil.py
- jupyter_client/tests/test_jsonutil.py
which have moved to ipython_kernel
> remove kernel-side json utils

- jupyter_client/kernelspec.py
- jupyter_client/tests/test_kernelspec.py
use SYSTEM_JUPYTER_PATH from core instead
sibling to jupyter/jupyter_notebook#64
> remove SYSTEM_KERNEL_DIRS

- .travis.yml
- jupyter_client/consoleapp.py
- jupyter_client/kernelspec.py
- jupyter_client/kernelspecapp.py
- jupyter_client/manager.py
- jupyter_client/win_interrupt.py
- requirements.txt
- setup.py
> ipython_kernel is now ipykernel

- jupyter_client/kernelspec.py
Would have help with https://github.com/jupyter/notebook/pull/76
But data_dir was tampered with.
> Add debug statement to see where kernelspec list find kernels.

- docs/api/client.rst
- docs/api/index.rst
- docs/api/manager.rst
> Document client and manager classes as top-level in package

- jupyter_client/connect.py
and warn about it if specified. For signature compatibility with pre-4.0.
> add ignored profile kwarg

- jupyter_client/kernelspec.py
Closes gh-35, in concert with jupyter/notebook#168
> Make the native kernel available without needing to install it

- jupyter_client/kernelspecapp.py
> provide a way to output kernelspec as json

- scripts/jupyter-kernelspec
First pull request in jupyter project.
> fix shebang line

- jupyter_client/kernelspec.py
Between jupyter_client.kernelspec and ipykernel.kernelspec
Closes gh-46
> Use local imports to avoid circular module-level imports

- jupyter_client/kernelspecapp.py
pure json display of kernels informations
> add kernel spec to json kernelspec list output

- jupyter_client/client.py
- jupyter_client/consoleapp.py
- jupyter_client/manager.py
> Use instances of traits instead of trait classes

- docs/wrapperkernels.rst
migrated from https://github.com/ipython/ipython/pull/8684
> Updates instructions for simple wrapper kernel

- jupyter_client/manager.py
There was a dictionary order dependent issue if kernel_name got set before kernel_spec_manager. Turning a couple of traitlets into properties avoids that.
Closes gh-56 (hopefully) - @danielballan, can you test this?
kernel_spec is cached, so it only gets looked up once. Changing kernel_name or kernel_spec_manager invalidates the cache.
This would break passing kernel_spec directly to KernelManager, but I don't think we do that anywhere. It's hard to know with traitlets whether the ability to pass a given attribute is by design or just
incidental.
> Make ipykernel and kernel_spec properties instead of traitlets

- jupyter_client/kernelspecapp.py
sort kernelspecs by path priority
Example output:
```
Available kernels:
pypy                  /Users/minrk/.ipython/kernels/pypy
jskernel              /Users/minrk/.ipython/kernels/jskernel
py2-stable            /Users/minrk/.ipython/kernels/py2-stable
nodejs                /Users/minrk/.ipython/kernels/nodejs
hashdist-my-kernel    /Users/minrk/.ipython/kernels/hashdist-my-kernel
julia-0.4             /Users/minrk/.ipython/kernels/julia-0.4
python2               /Users/minrk/Library/Jupyter/kernels/python2
pypyjs                /Users/minrk/Library/Jupyter/kernels/pypyjs
cling                 /Users/minrk/Library/Jupyter/kernels/cling
python3               /Users/minrk/Library/Jupyter/kernels/python3
ipython3              /Users/minrk/Library/Jupyter/kernels/ipython3
ir …
```
> show paths in human kernelspec list output

- jupyter_client/manager.py
helps debugging kernel startup
> log kernel command at debug level

- jupyter_client/kernelspecapp.py
> recommend `--user` when install fails with permission errors

- jupyter_client/session.py
My stab at #62 
I'm not sure if this is the best place to put this or if it covers everything that might be useful.
> Session debug prints incoming messages

- docs/api/index.rst
- docs/conf.py
- docs/index.rst
- docs/messaging.rst
Add table of contents and captions. Add "important" note to table of contents about the messaging protocol.
> Update table of contents and add captions

- setup.py
> use setuptools entrypoints

- jupyter_client/kernelspecapp.py
and include an example
closes #72
> note source directory in kernelspec install

- jupyter_client/consoleapp.py
- jupyter_client/manager.py
- jupyter_client/multikernelmanager.py
make it the default behavior, rather than hardcoded parameter in MKM
closes #94
> allow autorestart to be configurable

- jupyter_client/launcher.py
> Protect `popen`

- jupyter_client/connect.py
- jupyter_client/tests/test_connect.py
Closes #50.
This doesn't feel like the right approach so opening up this PR for advisement.
cc/ @minrk
> Add kernel spec name to connection file

- jupyter_client/session.py
> warn if message signing is disabled

- docs/messaging.rst
> remove source from display_data docs

- docs/messaging.rst
> Clarify execute_result in messaging doc for IOPub

- jupyter_client/consoleapp.py
Fixes https://github.com/jupyter/jupyter_console/issues/61
> DOC: Add info about how to disable confirm exit in the config file.

- jupyter_client/consoleapp.py
> Fix JupyterConsoleApp.confirm_exit config reference

- jupyter_client/kernelspecapp.py
for better symmetry with nbextensions, etc.
> add `--sys-prefix` arg to kernelspec install

- docs/changelog.rst
Main public-facing change: add `--sys-prefix` arg.
> notes for 4.3 release

- docs/messaging.rst
> Make stdin messaging docs not IPython specific

- docs/messaging.rst
- indicate that status=error doesn't require any fields from when status=ok to be defined
- mention that status messages can be used to fence output (with async output caveat)
closes jupyter/notebook#1576
closes jupyter/notebook#1575
> Clarifications on some of the specification

- docs/kernels.rst
Closes https://github.com/jupyter/notebook/issues/1581
> Add doc text to list files found in kernel directory

- jupyter_client/adapter.py
Might address issues validating parent_header on adapted messages
cf https://github.com/jupyter/jupyterlab/issues/470
> adapt parent_header as well as header

- jupyter_client/connect.py
- jupyter_client/tests/test_connect.py
for loading connection_info from a dict, not just files.
> add load_connection_info

- docs/conf.py
- docs/environment.yml
- readthedocs.yml
> Update the documentation build to use conda

- docs/messaging.rst
> declare the 'buffers' name in the messaging doc

- docs/messaging.rst
Closes https://github.com/jupyter/jupyter_client/issues/214
> Document metadata for JSON mime-type

- setup.cfg
- setup.py
> Enable warnings by default

- docs/messaging.rst
> More info about history messaging

- jupyter_client/session.py
- jupyter_client/tests/test_session.py
Thanks to @minrk for suggesting code.
Should fix https://github.com/ipython/ipywidgets/issues/1059
> Check that buffers in a session send support the buffer protocol.

- docs/messaging.rst
> Add note on compatibility to messaging spec

- docs/api/client.rst
- docs/changelog.rst
- jupyter_client/blocking/client.py
Changelog, and update a few API docs.
> Update docs for 5.0

- docs/environment.yml
- docs/requirements.txt
- docs/wrapperkernels.rst
> Document send_response() method

- .travis.yml
To get the correct version of IPython
> Update pip on Travis before running tests

- jupyter_client/connect.py
- jupyter_client/consoleapp.py
- jupyter_client/tests/test_connect.py
- find_connection_file returns abspath
- add missing cwd to `--existing` search path
> test find_connection_file with local and absolute paths

- docs/changelog.rst
> changelog for 5.1

- CONTRIBUTING.md
- README.md
> #268: README on setting up the development environment

- setup.py
@minrk I think you accidentally removed these in #284
> Restore entry_points

- docs/api/kernelspec.rst
- docs/kernels.rst
(This is a followup to #274.)
/cc @rgbkrk
> Clarify recommended use of metadata in docs.

- docs/conf.py
Closes #295 
Rendering of updated version on my test system: http://test-jupclient.readthedocs.io/en/execution/messaging.html#execute
> update intersphinx target

- jupyter_client/manager.py
to help inqiure on this https://github.com/jupyter/jupyter_client/issues/329
> more complete error message

- .gitignore
Add few IDE related files to gitignore
> Update gitignore configuration

- .travis.yml
Looks like coverage 5.0.0a3 have issues.
> try to fix coverage

- docs/messaging.rst
> Clarify stop_on_error documentation.

- jupyter_client/tests/test_jsonutil.py
Dateutils complains otherwise.
> Remove some warning in test, create all dates as UTC.

- docs/kernels.rst
> Add xeus to the documentation on how to write a kernel for Jupyter

- docs/wrapperkernels.rst
Clean up outdated Octave reference and add notes about Metakernels.
cc @dsblank
> Update wrapper kernel docs

- jupyter_client/ioloop/manager.py
- jupyter_client/multikernelmanager.py
> Backport 5.x PR #477: Exposes control channel in public API

- jupyter_client/__init__.py
- jupyter_client/asynchronous/client.py
- jupyter_client/ioloop/__init__.py
- jupyter_client/ioloop/manager.py
- jupyter_client/ioloop/restarter.py
- jupyter_client/manager.py
- jupyter_client/multikernelmanager.py
- jupyter_client/tests/test_kernelmanager.py
- jupyter_client/tests/test_multikernelmanager.py
> Async subclasses

- docs/kernels.rst
> Fix rst for xeus kernel list

- jupyter_client/localinterfaces.py
Closes https://github.com/jupyter/jupyter_client/issues/466
> Fix for issue #466, Windows localhost ip addresses

- jupyter_client/kernelspecapp.py
> Support answer_yes when removing kernel specs

- jupyter_client/kernelspec.py
> Fix project name

- CHANGELOG.md
Automated Changelog Entry for 7.0.2 on master
After merging this PR run the "Draft Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Version Spec | 7.0.2 |
| Since | v7.0.1 |
> Automated Changelog Entry for 7.0.2 on master

- jupyter_client/tests/test_jsonutil.py
> Add test for serializing bytes

- .github/workflows/check-release.yml
See https://github.com/jupyter/jupyter_client/issues/726#issuecomment-998965728
> Replace master with main

- MANIFEST.in
- setup.py
cf https://peps.python.org/pep-0561/
cf https://github.com/jupyter-server/jupyter_server/pull/779
> Include py.typed file

- .github/workflows/main.yml
- jupyter_client/manager.py
- jupyter_client/multikernelmanager.py
- jupyter_client/tests/test_kernelmanager.py
- jupyter_client/tests/test_multikernelmanager.py
Reverts jupyter/jupyter_client#848
> Revert "Backport PR #845: Fix pending kernels again"

- jupyter_client/manager.py
- jupyter_client/multikernelmanager.py
- tests/test_kernelmanager.py
- tests/test_multikernelmanager.py
Reverts jupyter/jupyter_client#845
Will replace with logic from #852
> Revert "Fix pending kernels again"

- tests/conftest.py
Handle new recommended behavior of `jupyter_core`.
> Use platform dirs in tests

- .github/workflows/main.yml
- codecov.yml
- pyproject.toml
- Add coverage report config to ignore common patterns
- Add codecov config file
> Add coverage config

- .github/workflows/main.yml
- pyproject.toml
- tests/test_session.py
- tests/test_ssh.py
- Ensure hatch scripts on Windows
- Add more coverage to ssh and session
> More coverage

- .github/workflows/main.yml
- .pre-commit-config.yaml
- docs/conf.py
- jupyter_client/_version.py
- jupyter_client/adapter.py
- jupyter_client/asynchronous/client.py
- jupyter_client/blocking/client.py
- jupyter_client/channels.py
- jupyter_client/channelsabc.py
- jupyter_client/clientabc.py
- jupyter_client/consoleapp.py
- jupyter_client/ioloop/manager.py
- jupyter_client/ioloop/restarter.py
- jupyter_client/kernelapp.py
- jupyter_client/kernelspec.py
- jupyter_client/kernelspecapp.py
- jupyter_client/manager.py
- jupyter_client/managerabc.py
- jupyter_client/provisioning/factory.py
- jupyter_client/provisioning/local_provisioner.py
- jupyter_client/runapp.py
- jupyter_client/session.py
- jupyter_client/ssh/forward.py
- jupyter_client/threaded.py
- pyproject.toml
cf https://github.com/jupyter-server/jupyter_server
> Add more ci checks

- jupyter_client/kernelspecapp.py
> Fix json_output in kernelspec app

- .pre-commit-config.yaml
- jupyter_client/channels.py
- jupyter_client/client.py
- jupyter_client/connect.py
- jupyter_client/ioloop/manager.py
- jupyter_client/jsonutil.py
- jupyter_client/kernelspec.py
- jupyter_client/launcher.py
- jupyter_client/localinterfaces.py
- jupyter_client/manager.py
- jupyter_client/multikernelmanager.py
- jupyter_client/provisioning/factory.py
- jupyter_client/provisioning/local_provisioner.py
- jupyter_client/restarter.py
- jupyter_client/runapp.py
- jupyter_client/session.py
- jupyter_client/ssh/tunnel.py
- jupyter_client/utils.py
- pyproject.toml
- tests/test_jsonutil.py
- tests/test_provisioning.py
The biggest change is around `flake8-errmsg` (EM), improving our error messages.
> Adopt more ruff rules

- .github/workflows/main.yml
- README.md
- codecov.yml
- pyproject.toml
cf https://github.com/jupyterlab/maintainer-tools/pull/189
> Use local coverage

- .github/workflows/main.yml
- .pre-commit-config.yaml
- jupyter_client/ioloop/manager.py
- jupyter_client/kernelspec.py
- pyproject.toml
Also consolidate config into `pre-commit`
> Update typing for traitlets 5.13

- .github/workflows/downstream.yml
should not include the `pip install` part
> fix invocation of pip for nbconvert downstream

- .github/workflows/main.yml
- run on ubuntu to get proper shell, possibly avoid weird error
- adjust check for docs:api run
this should get things back to green
> Fix docs check
